package io.vidocq.vauban.api;

/**
 * SPI implemented (and generated by the APT or the {@code vauban-maven-plugin}) inside an
 * application module to let the Vauban container instantiate that module's components — beans,
 * contexts, synthetic creators/disposers/observers — <strong>without reflection and without
 * {@code opens … to io.vidocq.vauban.core}</strong>.
 *
 * <p>It lives in {@code vauban-api} (not {@code vauban-core}) on purpose: a module declares it as a
 * service, so the service type must be compile-visible to that module's {@code module-info} — just
 * like {@code jakarta.enterprise.inject.build.compatible.spi.BuildCompatibleExtension} lives in the
 * CDI API, not in an implementation. Wrappers depend on {@code vauban-core} at test scope only, so
 * the SPI cannot live there.
 *
 * <p>The generated implementation instantiates each component in-module
 * ({@code new HelloResource()}), so the constructor call happens from code that already has
 * full access to its own package. The module exposes it as a service:
 *
 * <pre>{@code
 * provides io.vidocq.vauban.api.VaubanComponentProvider with app._VaubanComponents;
 * }</pre>
 *
 * and {@code vauban-core} loads it via {@link java.util.ServiceLoader} — the module system
 * performs the instantiation of the provider itself, so no qualified {@code opens} is needed.
 *
 * <p>This replaces the runtime {@code privateLookupIn}/{@code newInstance} path that forced
 * application modules to open their packages to the container on the strict module path.
 */
public interface VaubanComponentProvider {

    /**
     * Instantiates the component with the given fully-qualified name using its no-argument
     * constructor, or returns {@code null} if this provider does not own that component
     * (so the container can consult the next provider or fall back to reflection).
     *
     * @param className fully-qualified name of the component class to instantiate
     * @return a fresh instance, or {@code null} if not owned by this provider
     */
    Object create(String className);

    /**
     * Instantiates the component with the given fully-qualified name using its injected
     * constructor, passing the dependency values {@code vauban-core} has already resolved (in
     * declared parameter order). The provider performs the {@code new X(args…)} call in-module
     * so the constructor invocation needs no reflection and no {@code opens} — argument
     * resolution (qualifiers, generics, injection points) stays in the container.
     *
     * <p>The default delegates to {@link #create(String)} when there are no arguments, and
     * returns {@code null} otherwise, so providers that only handle no-arg components keep
     * working and the container falls back to reflection for arg-bearing ones.
     *
     * @param className fully-qualified name of the component class to instantiate
     * @param args      already-resolved constructor arguments, in declared order
     * @return a fresh instance, or {@code null} if not owned by this provider
     */
    default Object create(String className, Object[] args) {
        return (args == null || args.length == 0) ? create(className) : null;
    }

    /**
     * Writes an already-resolved value into an {@code @Inject} field of {@code bean}, in-module, so
     * the container needs neither {@code unreflectSetter}/{@code setAccessible} nor an
     * {@code opens … to io.vidocq.vauban.core} for field injection. The generated implementation
     * performs a plain in-package field assignment ({@code ((Bean) bean).field = (Type) value}),
     * which is a bytecode {@code putfield} — no reflection.
     *
     * <p>{@code vauban-core} resolves the value (qualifiers, generics, scopes, injection points) and
     * only delegates the assignment. A provider must own {@code className} <em>and</em> live in the
     * same package as the field's declaring class (a {@code putfield} cannot reach a package-private
     * field across packages); otherwise it returns {@code false} and the container falls back to
     * reflective field injection (which still needs the qualified {@code opens}).
     *
     * <p>The default returns {@code false}, so providers that only instantiate components keep
     * working and the container keeps injecting their fields reflectively.
     *
     * @param bean      the bean instance whose field is written
     * @param className fully-qualified name of the field's declaring class
     * @param fieldName name of the {@code @Inject} field to assign
     * @param value     the container-resolved value to assign (may be {@code null})
     * @return {@code true} if this provider performed the assignment; {@code false} otherwise
     */
    default boolean injectField(Object bean, String className, String fieldName, Object value) {
        return false;
    }
}
