/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.vauban.api;

/**
 * SPI implemented (and generated by the APT or the {@code vauban-maven-plugin}) inside an
 * application module to let the Vauban container instantiate that module's components — beans,
 * contexts, synthetic creators/disposers/observers — <strong>without reflection and without
 * {@code opens … to io.vidocq.vauban.core}</strong>.
 *
 * <p>It lives in {@code vauban-api} (not {@code vauban-core}) on purpose: a module declares it as a
 * service, so the service type must be compile-visible to that module's {@code module-info} — just
 * like {@code jakarta.enterprise.inject.build.compatible.spi.BuildCompatibleExtension} lives in the
 * CDI API, not in an implementation. Wrappers depend on {@code vauban-core} at test scope only, so
 * the SPI cannot live there.
 *
 * <p>The generated implementation instantiates each component in-module
 * ({@code new HelloResource()}), so the constructor call happens from code that already has
 * full access to its own package. The module exposes it as a service:
 *
 * <pre>{@code
 * provides io.vidocq.vauban.api.VaubanComponentProvider with app._VaubanComponents;
 * }</pre>
 *
 * and {@code vauban-core} loads it via {@link java.util.ServiceLoader} — the module system
 * performs the instantiation of the provider itself, so no qualified {@code opens} is needed.
 *
 * <p>This replaces the runtime {@code privateLookupIn}/{@code newInstance} path that forced
 * application modules to open their packages to the container on the strict module path.
 */
public interface VaubanComponentProvider {

    /**
     * Instantiates the component with the given fully-qualified name using its no-argument
     * constructor, or returns {@code null} if this provider does not own that component
     * (so the container can consult the next provider or fall back to reflection).
     *
     * @param className fully-qualified name of the component class to instantiate
     * @return a fresh instance, or {@code null} if not owned by this provider
     */
    Object create(String className);

    /**
     * What the annotation type {@code annotationClassName} declares — its members, their defaults and
     * the ones annotated {@code @Nonbinding} — or {@code null} if this provider does not own that
     * type, so the container reads the declaration itself.
     *
     * <p>CDI compares qualifiers and interceptor bindings by these rules; reading them here is what
     * lets the container match without touching the annotation type at run time.
     *
     * @param annotationClassName fully-qualified name of the annotation type
     * @return what it declares, or {@code null} if not owned by this provider
     */
    default AnnotationTypeMetadata annotationMetadata(String annotationClassName) {
        return null;
    }

    /**
     * The member values of {@code annotation}, by member name, read by calling its members directly —
     * or {@code null} if this provider does not own its type, so the container reads them reflectively.
     *
     * <p>Every member is present, including those the annotation leaves at their default. Array values
     * are copies: a caller may keep or change them.
     *
     * @param annotation the instance to read
     * @return its member values, or {@code null} if not owned by this provider
     */
    default java.util.Map<String, Object> readAnnotation(java.lang.annotation.Annotation annotation) {
        return null;
    }

    /**
     * An instance of {@code annotationClassName} carrying {@code members}, every other member taking
     * its default — or {@code null} if this provider does not own that type, so the container builds a
     * {@link java.lang.reflect.Proxy} instead.
     *
     * <p>The instance honours {@link java.lang.annotation.Annotation#equals},
     * {@link java.lang.annotation.Annotation#hashCode} and
     * {@link java.lang.annotation.Annotation#toString}, so application code can compare it with a
     * literal of its own.
     *
     * @param annotationClassName fully-qualified name of the annotation type
     * @param members             the member values to carry, by member name
     * @return an instance, or {@code null} if not owned by this provider
     */
    default java.lang.annotation.Annotation annotationLiteral(String annotationClassName,
            java.util.Map<String, Object> members) {
        return null;
    }

    /**
     * Instantiates the component with the given fully-qualified name using its injected
     * constructor, passing the dependency values {@code vauban-core} has already resolved (in
     * declared parameter order). The provider performs the {@code new X(args…)} call in-module
     * so the constructor invocation needs no reflection and no {@code opens} — argument
     * resolution (qualifiers, generics, injection points) stays in the container.
     *
     * <p>The default delegates to {@link #create(String)} when there are no arguments, and
     * returns {@code null} otherwise, so providers that only handle no-arg components keep
     * working and the container falls back to reflection for arg-bearing ones.
     *
     * @param className fully-qualified name of the component class to instantiate
     * @param args      already-resolved constructor arguments, in declared order
     * @return a fresh instance, or {@code null} if not owned by this provider
     */
    default Object create(String className, Object[] args) {
        return (args == null || args.length == 0) ? create(className) : null;
    }

    /**
     * Writes an already-resolved value into an {@code @Inject} field of {@code bean}, in-module, so
     * the container needs neither {@code unreflectSetter}/{@code setAccessible} nor an
     * {@code opens … to io.vidocq.vauban.core} for field injection. The generated implementation
     * performs a plain in-package field assignment ({@code ((Bean) bean).field = (Type) value}),
     * which is a bytecode {@code putfield} — no reflection.
     *
     * <p>{@code vauban-core} resolves the value (qualifiers, generics, scopes, injection points) and
     * only delegates the assignment. A provider must own {@code className} <em>and</em> live in the
     * same package as the field's declaring class (a {@code putfield} cannot reach a package-private
     * field across packages); otherwise it returns {@code false} and the container falls back to
     * reflective field injection (which still needs the qualified {@code opens}).
     *
     * <p>The default returns {@code false}, so providers that only instantiate components keep
     * working and the container keeps injecting their fields reflectively.
     *
     * @param bean      the bean instance whose field is written
     * @param className fully-qualified name of the field's declaring class
     * @param fieldName name of the {@code @Inject} field to assign
     * @param value     the container-resolved value to assign (may be {@code null})
     * @return {@code true} if this provider performed the assignment; {@code false} otherwise
     */
    default boolean injectField(Object bean, String className, String fieldName, Object value) {
        return false;
    }

    /**
     * Instantiates the client proxy {@code <Bean>_ClientProxy} of a normal-scoped bean in-module and
     * wires its delegate, so the container needs neither a reflective {@code newInstance}/
     * {@code $$setDelegate} nor an {@code opens … to io.vidocq.vauban.core} — and crucially no
     * {@code exports} of the bean package — to create the proxy. The generated implementation performs
     * {@code new <Bean>_ClientProxy()} followed by {@code proxy.$$setDelegate(delegate)}, both
     * in-package (a bytecode {@code new} + {@code invokevirtual}), so no reflection.
     *
     * <p>{@code vauban-core} builds the {@code delegate} supplier (it resolves the contextual instance
     * of the bean per call) and only delegates the in-module instantiation + wiring. A provider must
     * own {@code proxyClassName} — its APT-generated {@code _ClientProxy} lives in the provider's own
     * package — otherwise it returns {@code null} and the container falls back to runtime proxy
     * generation + reflective instantiation (which needs the bean package opened/exported).
     *
     * <p>The default returns {@code null}, so providers that predate this method keep working and the
     * container keeps creating their proxies reflectively.
     *
     * @param proxyClassName fully-qualified name of the {@code <Bean>_ClientProxy} class to instantiate
     * @param delegate       supplier of the contextual instance the proxy forwards calls to
     * @return a fresh, delegate-wired proxy instance, or {@code null} if not owned by this provider
     */
    default Object createClientProxy(String proxyClassName, java.util.function.Supplier<?> delegate) {
        return null;
    }

    /**
     * Sentinel returned by {@link #invoke} when the provider does not own the requested method, so
     * the container can tell "not handled" apart from a {@code void}/{@code null} return and fall
     * back to reflective invocation. Identity comparison ({@code ==}) is intentional.
     */
    Object NOT_INVOKED = new Object();

    /**
     * Invokes a method (producer, observer, disposer, lifecycle callback or initializer) of one of
     * this module's components in-module, so the container needs neither {@code unreflect}/
     * {@code setAccessible} nor an {@code opens … to io.vidocq.vauban.core} to call it. The generated
     * implementation performs a direct in-package call ({@code ((Decl) target).method((P) args[0],…)}
     * — a bytecode {@code invokevirtual}/{@code invokestatic}), returning the method result (or
     * {@code null} for a {@code void} method).
     *
     * <p>{@code vauban-core} resolves the arguments (event payload, injected parameters, qualifiers)
     * and only delegates the call. A provider must own {@code className} <em>and</em> live in the
     * same package as the declaring class (a direct call cannot reach a package-private method across
     * packages); otherwise it returns {@link #NOT_INVOKED} and the container falls back to reflective
     * invocation (which still needs the qualified {@code opens}). Exceptions thrown by the target
     * method propagate as-is (no {@code InvocationTargetException} wrapping).
     *
     * <p>The default returns {@link #NOT_INVOKED}, so providers that only instantiate/inject keep
     * working and the container keeps invoking their methods reflectively.
     *
     * @param target    the instance to call the method on, or {@code null} for a static method
     * @param className  fully-qualified name of the method's declaring class
     * @param methodId   method identity key {@code name(paramErasure,…)} (erased parameter types,
     *                   in declared order), disambiguating overloads
     * @param args       the container-resolved arguments, in declared order
     * @return the method's return value ({@code null} for {@code void}), or {@link #NOT_INVOKED} if
     *         this provider does not own the method
     */
    default Object invoke(Object target, String className, String methodId, Object[] args) {
        return NOT_INVOKED;
    }

    /**
     * Hands the provider's own full-privilege lookup to the container, through a grant only the
     * container can create. The generated implementation is
     * {@code grant.accept(java.lang.invoke.MethodHandles.lookup())}: its lookup class is the
     * provider, so the lookup carries the access of the provider's package and module, nothing more.
     *
     * <p>The container passes it on, for one managed class of this package at a time, to the
     * extension modules it trusts ({@code io.vidocq.vauban.core.access.ModuleLookups}), which can
     * then reach a member the application did not open — for instance a {@code private}
     * {@code @Fallback} method. Nobody else can obtain it: a {@link ModuleLookupGrant} cannot be
     * created outside {@code io.vidocq.vauban.core}, and the container accepts only a lookup whose
     * lookup class is this provider.</p>
     *
     * <p>The default grants nothing (providers generated before this method existed).</p>
     *
     * @param grant the container's grant
     */
    default void grantModuleLookup(ModuleLookupGrant grant) {
    }

    /**
     * What this provider runs in-module — the components it instantiates, the fields it injects, the methods it
     * invokes and the client proxies it creates — for diagnostics such as the Vidocq dev console. The container never
     * dispatches on it. Both generators render it from the very lists that feed {@link #create}, {@link #injectField},
     * {@link #invoke} and {@link #createClientProxy}, so it cannot diverge from them.
     *
     * <p>The default returns {@code null}: a provider that predates this method declares nothing, and its coverage is
     * reported as unknown rather than as reflection.
     *
     * @return what this provider covers, or {@code null} if it does not say
     */
    default GeneratedCoverage coverage() {
        return null;
    }
}
