<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
         >
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.vidocq</groupId>
        <artifactId>vidocq-parent</artifactId>
        <version>0.1.1</version>
    </parent>

    <groupId>io.vidocq.vauban</groupId>
    <artifactId>vauban-parent</artifactId>
    <version>0.1.1</version>
    <packaging>pom</packaging>

    <name>Vauban</name>
    <description>CDI 4.1 container, Java Modules native</description>
    <url>https://codeberg.org/Vidocq/vauban</url>

    <developers>
        <developer>
            <name>Yann Blazart</name>
            <email>yann.blazart@gmail.com</email>
        </developer>
        <developer>
            <name>Antoine Sabot-Durand</name>
            <email>antoine@sabot-durand.net</email>
        </developer>
    </developers>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:https://codeberg.org/Vidocq/vauban.git</connection>
        <developerConnection>scm:git:ssh://git@codeberg.org/Vidocq/vauban.git</developerConnection>
        <url>https://codeberg.org/Vidocq/vauban</url>
    </scm>

    <modules>
        <module>vauban-api</module>
        <module>vauban-classloader-spi</module>
        <module>vauban-core</module>
        <module>vauban-indexer</module>
        <module>vauban-processor</module>
        <module>vauban-sjar</module>
        <module>vauban-junit</module>
        <module>vauban-maven-plugin</module>
        <module>vauban-test-suite</module>
        <module>vauban-tck-runner</module>
        <module>vauban-examples</module>
    </modules>

    <properties>
        <jakarta.cdi.version>4.1.0</jakarta.cdi.version>

        <!-- Quality -->
        <sonar.projectKey>vidocq-vauban</sonar.projectKey>
        <sonar.java.source>25</sonar.java.source>
        <sonar.coverage.jacoco.xmlReportPaths>${project.build.directory}/site/jacoco/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
        <sonar.exclusions>**/generated/**</sonar.exclusions>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Jakarta CDI API -->
            <dependency>
                <groupId>jakarta.enterprise</groupId>
                <artifactId>jakarta.enterprise.cdi-api</artifactId>
                <version>${jakarta.cdi.version}</version>
            </dependency>
            <dependency>
                <groupId>jakarta.enterprise</groupId>
                <artifactId>jakarta.enterprise.lang-model</artifactId>
                <version>${jakarta.cdi.version}</version>
            </dependency>

            <!-- Inter-project dependencies -->
            <dependency>
                <groupId>io.vidocq.vauban</groupId>
                <artifactId>vauban-indexer</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.vidocq.vauban</groupId>
                <artifactId>vauban-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.vidocq.vauban</groupId>
                <artifactId>vauban-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.vidocq.vauban</groupId>
                <artifactId>vauban-processor</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.vidocq.vauban</groupId>
                <artifactId>vauban-junit</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.vidocq.vauban</groupId>
                <artifactId>vauban-classloader-spi</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.vidocq.vauban</groupId>
                <artifactId>vauban-sjar</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.sonarsource.scanner.maven</groupId>
                    <artifactId>sonar-maven-plugin</artifactId>
                    <version>5.1.0.4751</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
