/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.vauban.core.container;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLStreamHandler;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.Enumeration;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("VaubanContainer.Builder.scanClasspath()")
class ScanClasspathTest {

    @Test
    @DisplayName("discovers beans listed in META-INF/vauban-beans.list")
    void shouldDiscoverBeansFromBeansList() {
        // Create a custom ClassLoader that serves a synthetic vauban-beans.list
        var beansListContent = """
                # Generated by vauban-maven-plugin
                java.util.ArrayList
                java.util.HashMap
                """;

        var cl = new BeansListClassLoader(beansListContent, getClass().getClassLoader());

        // scanClasspath should add the listed classes as bean classes
        // We can't fully boot the container (these aren't CDI beans),
        // but we can verify the builder accepts them without error
        var builder = VaubanContainer.builder().classLoader(cl).scanClasspath();
        assertNotNull(builder);
    }

    @Test
    @DisplayName("ignores comments and blank lines in beans list")
    void shouldIgnoreCommentsAndBlankLines() {
        var beansListContent = """
                # This is a comment

                java.util.ArrayList

                # Another comment
                java.util.HashMap
                """;

        var cl = new BeansListClassLoader(beansListContent, getClass().getClassLoader());
        var builder = VaubanContainer.builder().classLoader(cl).scanClasspath();
        assertNotNull(builder);
    }

    @Test
    @DisplayName("handles missing vauban-beans.list gracefully")
    void shouldHandleMissingBeansList() {
        // Use a ClassLoader that has no vauban-beans.list
        var cl = new EmptyBeansListClassLoader(getClass().getClassLoader());
        var builder = VaubanContainer.builder().classLoader(cl).scanClasspath();
        assertNotNull(builder);
    }

    @Test
    @DisplayName("skips unknown classes without throwing")
    void shouldSkipUnknownClasses() {
        var beansListContent = """
                com.nonexistent.FakeClass
                java.util.ArrayList
                """;

        var cl = new BeansListClassLoader(beansListContent, getClass().getClassLoader());
        var builder = VaubanContainer.builder().classLoader(cl).scanClasspath();
        assertNotNull(builder);
    }

    @Test
    @DisplayName("names a listed class it cannot load, instead of dropping it in silence (grimm#15)")
    void shouldReportUnloadableListedClass() {
        // An archive's beans vanished without a word when its package was split into another
        // module: every class of its list failed to load, and the scan said nothing.
        var beansListContent = """
                com.nonexistent.FakeClass
                java.util.ArrayList
                """;
        // The tests run inside io.vidocq.vauban.core, which does not read java.logging, the backend of
        // System.Logger here: read it for the capture.
        getClass().getModule().addReads(ModuleLayer.boot().findModule("java.logging").orElseThrow());
        var out = new java.io.ByteArrayOutputStream();
        var handler = new java.util.logging.StreamHandler(out, new java.util.logging.SimpleFormatter());
        handler.setLevel(java.util.logging.Level.WARNING);
        var logger = java.util.logging.Logger.getLogger(ContainerScanner.class.getName());
        logger.addHandler(handler);
        try {
            var cl = new BeansListClassLoader(beansListContent, getClass().getClassLoader());
            VaubanContainer.builder().classLoader(cl).scanClasspath();
        } finally {
            handler.flush();
            logger.removeHandler(handler);
        }

        // The handler lets warnings and above through, and the formatter localises the level's name.
        var logged = out.toString(StandardCharsets.UTF_8);
        assertTrue(logged.contains("com.nonexistent.FakeClass"),
                "expected a warning naming the class; got: " + logged);
    }

    /**
     * Custom ClassLoader that serves a synthetic META-INF/vauban-beans.list.
     */
    private static class BeansListClassLoader extends ClassLoader {
        private final String content;

        BeansListClassLoader(String content, ClassLoader parent) {
            super(parent);
            this.content = content;
        }

        @Override
        public Enumeration<URL> getResources(String name) throws IOException {
            if ("META-INF/vauban-beans.list".equals(name)) {
                var url = new URL("memory", "", 0, "/vauban-beans.list",
                        new URLStreamHandler() {
                            @Override
                            protected URLConnection openConnection(URL u) {
                                return new URLConnection(u) {
                                    @Override public void connect() {}
                                    @Override public InputStream getInputStream() {
                                        return new ByteArrayInputStream(
                                                content.getBytes(StandardCharsets.UTF_8));
                                    }
                                };
                            }
                        });
                return Collections.enumeration(java.util.List.of(url));
            }
            return super.getResources(name);
        }
    }

    private static class EmptyBeansListClassLoader extends ClassLoader {
        EmptyBeansListClassLoader(ClassLoader parent) {
            super(parent);
        }

        @Override
        public Enumeration<URL> getResources(String name) throws IOException {
            if ("META-INF/vauban-beans.list".equals(name)) {
                return Collections.emptyEnumeration();
            }
            return super.getResources(name);
        }
    }
}
