package io.vidocq.vauban.core.container;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLStreamHandler;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.Enumeration;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("VaubanContainer.Builder.scanClasspath()")
class ScanClasspathTest {

    @Test
    @DisplayName("discovers beans listed in META-INF/vauban-beans.list")
    void shouldDiscoverBeansFromBeansList() {
        // Create a custom ClassLoader that serves a synthetic vauban-beans.list
        var beansListContent = """
                # Generated by vauban-maven-plugin
                java.util.ArrayList
                java.util.HashMap
                """;

        var cl = new BeansListClassLoader(beansListContent, getClass().getClassLoader());

        // scanClasspath should add the listed classes as bean classes
        // We can't fully boot the container (these aren't CDI beans),
        // but we can verify the builder accepts them without error
        var builder = VaubanContainer.builder().classLoader(cl).scanClasspath();
        assertNotNull(builder);
    }

    @Test
    @DisplayName("ignores comments and blank lines in beans list")
    void shouldIgnoreCommentsAndBlankLines() {
        var beansListContent = """
                # This is a comment

                java.util.ArrayList

                # Another comment
                java.util.HashMap
                """;

        var cl = new BeansListClassLoader(beansListContent, getClass().getClassLoader());
        var builder = VaubanContainer.builder().classLoader(cl).scanClasspath();
        assertNotNull(builder);
    }

    @Test
    @DisplayName("handles missing vauban-beans.list gracefully")
    void shouldHandleMissingBeansList() {
        // Use a ClassLoader that has no vauban-beans.list
        var cl = new EmptyBeansListClassLoader(getClass().getClassLoader());
        var builder = VaubanContainer.builder().classLoader(cl).scanClasspath();
        assertNotNull(builder);
    }

    @Test
    @DisplayName("skips unknown classes without throwing")
    void shouldSkipUnknownClasses() {
        var beansListContent = """
                com.nonexistent.FakeClass
                java.util.ArrayList
                """;

        var cl = new BeansListClassLoader(beansListContent, getClass().getClassLoader());
        var builder = VaubanContainer.builder().classLoader(cl).scanClasspath();
        assertNotNull(builder);
    }

    /**
     * Custom ClassLoader that serves a synthetic META-INF/vauban-beans.list.
     */
    private static class BeansListClassLoader extends ClassLoader {
        private final String content;

        BeansListClassLoader(String content, ClassLoader parent) {
            super(parent);
            this.content = content;
        }

        @Override
        public Enumeration<URL> getResources(String name) throws IOException {
            if ("META-INF/vauban-beans.list".equals(name)) {
                var url = new URL("memory", "", 0, "/vauban-beans.list",
                        new URLStreamHandler() {
                            @Override
                            protected URLConnection openConnection(URL u) {
                                return new URLConnection(u) {
                                    @Override public void connect() {}
                                    @Override public InputStream getInputStream() {
                                        return new ByteArrayInputStream(
                                                content.getBytes(StandardCharsets.UTF_8));
                                    }
                                };
                            }
                        });
                return Collections.enumeration(java.util.List.of(url));
            }
            return super.getResources(name);
        }
    }

    private static class EmptyBeansListClassLoader extends ClassLoader {
        EmptyBeansListClassLoader(ClassLoader parent) {
            super(parent);
        }

        @Override
        public Enumeration<URL> getResources(String name) throws IOException {
            if ("META-INF/vauban-beans.list".equals(name)) {
                return Collections.emptyEnumeration();
            }
            return super.getResources(name);
        }
    }
}
