package io.vidocq.vauban.core;

/**
 * SPI implemented (and generated by the APT) inside an application module to let
 * {@code vauban-core} instantiate that module's components — beans, contexts, synthetic
 * creators/disposers/observers — <strong>without reflection and without
 * {@code opens … to io.vidocq.vauban.core}</strong>.
 *
 * <p>The generated implementation instantiates each component in-module
 * ({@code new HelloResource()}), so the constructor call happens from code that already has
 * full access to its own package. The module exposes it as a service:
 *
 * <pre>{@code
 * provides io.vidocq.vauban.core.VaubanComponentProvider with app._VaubanComponents;
 * }</pre>
 *
 * and {@code vauban-core} loads it via {@link java.util.ServiceLoader} — the module system
 * performs the instantiation of the provider itself, so no qualified {@code opens} is needed.
 *
 * <p>This replaces the runtime {@code privateLookupIn}/{@code newInstance} path that forced
 * application modules to open their packages to the container on the strict module path.
 */
public interface VaubanComponentProvider {

    /**
     * Instantiates the component with the given fully-qualified name using its no-argument
     * constructor, or returns {@code null} if this provider does not own that component
     * (so the container can consult the next provider or fall back to reflection).
     *
     * @param className fully-qualified name of the component class to instantiate
     * @return a fresh instance, or {@code null} if not owned by this provider
     */
    Object create(String className);

    /**
     * Instantiates the component with the given fully-qualified name using its injected
     * constructor, passing the dependency values {@code vauban-core} has already resolved (in
     * declared parameter order). The provider performs the {@code new X(args…)} call in-module
     * so the constructor invocation needs no reflection and no {@code opens} — argument
     * resolution (qualifiers, generics, injection points) stays in the container.
     *
     * <p>The default delegates to {@link #create(String)} when there are no arguments, and
     * returns {@code null} otherwise, so providers that only handle no-arg components keep
     * working and the container falls back to reflection for arg-bearing ones.
     *
     * @param className fully-qualified name of the component class to instantiate
     * @param args      already-resolved constructor arguments, in declared order
     * @return a fresh instance, or {@code null} if not owned by this provider
     */
    default Object create(String className, Object[] args) {
        return (args == null || args.length == 0) ? create(className) : null;
    }
}
