package io.vidocq.vauban.core.interceptor;

import io.vidocq.vauban.core.interceptor.fixtures.GoldenBean;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.lang.classfile.ClassFile;
import java.lang.classfile.ClassModel;
import java.util.Arrays;
import java.util.stream.Collectors;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Verifies that {@link InterceptorSubclassGenerator#generate(Class)} after the shape-model
 * refactor:
 * <ol>
 *   <li><strong>Determinism</strong>: two successive calls with the same input produce
 *       byte-for-byte identical output (within the same JVM run).</li>
 *   <li><strong>Structural correctness</strong>: the generated bytecode parses correctly
 *       via {@link ClassFile#parse(byte[])} and contains all expected fields, constructors,
 *       and method overrides for the {@link GoldenBean} fixture.</li>
 * </ol>
 *
 * <p>A cross-run byte-for-byte comparison against a stored {@code .class} snapshot is not
 * used here because {@link Class#getDeclaredMethods()} order is not specified across JVM
 * restarts, which would make the constant-pool ordering non-deterministic.
 * The stored golden file in {@code src/test/resources/golden-intercepted/} is kept as a
 * reference artefact for manual inspection but is not byte-compared in CI.
 */
@DisplayName("Golden byte-for-byte equivalence after shape-model refactor")
class GoldenBytecodeTest {

    @Test
    @DisplayName("generate(GoldenBean) is deterministic within one JVM run")
    void generateIsDeterministic() {
        byte[] first = InterceptorSubclassGenerator.generate(GoldenBean.class).bytecode();
        byte[] second = InterceptorSubclassGenerator.generate(GoldenBean.class).bytecode();

        assertArrayEquals(first, second,
                "Two successive generate() calls must produce byte-for-byte identical output");
    }

    @Test
    @DisplayName("generated bytecode parses and contains expected structure")
    void generatedBytecodeHasExpectedStructure() {
        byte[] bytecode = InterceptorSubclassGenerator.generate(GoldenBean.class).bytecode();

        // Must parse without error
        ClassModel cm = ClassFile.of().parse(bytecode);

        String subclassName = "io/vidocq/vauban/core/interceptor/fixtures/GoldenBean$$Intercepted";
        assertEquals(subclassName, cm.thisClass().asInternalName(),
                "generated class name");
        assertEquals("io/vidocq/vauban/core/interceptor/fixtures/GoldenBean",
                cm.superclass().map(c -> c.asInternalName()).orElse(""),
                "superclass must be GoldenBean");

        var fields = cm.fields().stream()
                .map(f -> f.fieldName().stringValue())
                .collect(Collectors.toSet());
        assertTrue(fields.contains("$$manager"), "must have $$manager field");
        assertTrue(fields.contains("$$bindings"), "must have $$bindings field");
        assertTrue(fields.contains("$$constructorBindings"), "must have $$constructorBindings field");
        assertTrue(fields.contains("$$context"), "must have $$context field");

        var methodNames = cm.methods().stream()
                .map(m -> m.methodName().stringValue())
                .collect(Collectors.toSet());
        assertTrue(methodNames.contains("<init>"), "must have at least one constructor");
        assertTrue(methodNames.contains("$$init"), "must have $$init setter");
        assertTrue(methodNames.contains("$$super$voidNoArg"), "must have $$super$voidNoArg bridge");
        assertTrue(methodNames.contains("voidNoArg"), "must have voidNoArg override");
        assertTrue(methodNames.contains("$$super$primitiveParams"), "must have $$super$primitiveParams bridge");
        assertTrue(methodNames.contains("primitiveParams"), "must have primitiveParams override");
        assertTrue(methodNames.contains("intReturn"), "must have intReturn override");
        assertTrue(methodNames.contains("arrayParam"), "must have arrayParam override");
        // inherited from GoldenBeanSuper
        assertTrue(methodNames.contains("inheritedMethod"), "must have inheritedMethod override (inherited via getMethods())");
    }

    @Test
    @DisplayName("two constructors are generated for GoldenBean (no-arg + (String,int))")
    void twoConstructorsGenerated() {
        byte[] bytecode = InterceptorSubclassGenerator.generate(GoldenBean.class).bytecode();
        ClassModel cm = ClassFile.of().parse(bytecode);

        long ctorCount = cm.methods().stream()
                .filter(m -> "<init>".equals(m.methodName().stringValue()))
                .count();
        assertEquals(2L, ctorCount,
                "GoldenBean has 2 non-private constructors; subclass must mirror both");
    }

    @Test
    @DisplayName("GoldenBean$$Intercepted class name matches GeneratedInterceptedClass.className()")
    void classNameMatchesRecord() {
        var result = InterceptorSubclassGenerator.generate(GoldenBean.class);
        assertEquals(
                GoldenBean.class.getName() + "$$Intercepted",
                result.className());
    }
}
