/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.vauban.processor.codegen.proxy;

import io.vidocq.vauban.core.interceptor.TypeRef;
import io.vidocq.vauban.core.proxy.ClientProxyShape;
import io.vidocq.vauban.core.proxy.ClientProxyShape.ProxyMethodShape;

import javax.lang.model.element.TypeElement;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;
import java.util.List;

/**
 * Renders the {@code <Bean>_ClientProxy} normal-scoped client proxy as readable Java
 * <strong>source</strong> from the neutral {@link ClientProxyShape} — the source counterpart
 * of the shared bytecode {@link io.vidocq.vauban.core.proxy.ClientProxyEmitter}.
 *
 * <p>Emitting source (instead of Filer bytecode) lets the sibling generated source
 * {@code _VaubanComponents} reference {@code <Bean>_ClientProxy} by name and perform
 * {@code new <Bean>_ClientProxy()} in-module — so the container creates the proxy without reflection
 * and the bean package needs no {@code opens}/{@code exports}. This dissolves the same
 * "generated source cannot see Filer-emitted bytecode" wall that moved {@code $$Intercepted} to
 * source. The bytecode emitter is kept for the runtime classpath fallback and
 * the Maven plugin (post-compile, external jars).
 *
 * <p>Only generated for top-level normal-scoped beans with an accessible no-arg constructor (the
 * proxy constructor is {@code super()}); other beans keep the bytecode proxy + runtime fallback —
 * see the caller in {@code VaubanProcessor}.
 *
 * <p>The override set is decided by {@link ClientProxyShapeFromElements}, the naming
 * ({@code _ClientProxy}, {@code $$delegate}, {@code $$setDelegate}) by {@link ClientProxyShape} —
 * this class only renders. Each override forwards the call to the contextual instance:
 * {@code return ((Bean) $$delegate.get()).method(args);}.
 */
public final class ClientProxySourceRenderer {

    private static final String SUPPLIER = "java.util.function.Supplier";

    private ClientProxySourceRenderer() {}

    /** A generated source file: its fully-qualified class name and its textual content. */
    public record Generated(String className, String source) {}

    /** Render {@code <Bean>_ClientProxy} as Java source from the bean's {@link TypeElement}. */
    public static Generated render(TypeElement bean, Elements elements, Types types) {
        return render(ClientProxyShapeFromElements.from(bean, elements, types));
    }

    /** Render {@code shape.proxyClassName()} as Java source (proxy co-located with the bean). */
    public static Generated render(ClientProxyShape shape) {
        return renderAt(shape, shape.proxyClassName());
    }

    /**
     * Render the proxy at an explicit {@code proxyBinaryName} while still {@code extends}-ing the
     * shape's {@code beanBinaryName}. The co-located {@link #render(ClientProxyShape)} passes
     * {@code shape.proxyClassName()} (same package as the bean); the producer-proxy path (issue
     * #42) passes a name in the <em>producer's</em> package so the proxy of a fully-public class
     * from a non-opened module lands in-module, extending the external produced type by its
     * fully-qualified name. Cross-package correctness is guaranteed by the caller: only public
     * overridable methods are forwarded (a cast to the external type cannot reach protected or
     * package-private members from another package).
     */
    public static Generated renderAt(ClientProxyShape shape, String proxyBinaryName) {
        String beanBinary = shape.beanBinaryName();
        String beanSource = beanBinary.replace('$', '.');
        String proxyBinary = proxyBinaryName;
        int lastDot = proxyBinaryName.lastIndexOf('.');
        String pkg = lastDot >= 0 ? proxyBinaryName.substring(0, lastDot) : "";
        String proxySimple = lastDot >= 0 ? proxyBinaryName.substring(lastDot + 1) : proxyBinaryName;

        var sb = new StringBuilder();
        if (!pkg.isEmpty()) {
            sb.append("package ").append(pkg).append(";\n\n");
        }
        sb.append("// Generated by Vauban APT — normal-scoped client proxy of ").append(beanSource)
                .append(".\n");
        sb.append("// Forwards every business method to the contextual instance. Do not edit.\n");
        // @Vetoed: the proxy is instantiated explicitly, never discovered as a bean.
        sb.append("@jakarta.enterprise.inject.Vetoed\n");
        sb.append("@SuppressWarnings({\"unchecked\", \"rawtypes\"})\n");
        sb.append("public final class ").append(proxySimple).append(" extends ").append(beanSource)
                .append(" {\n\n");

        // Delegate supplier — set lazily via $$setDelegate (same contract as the bytecode emitter).
        sb.append("    private ").append(SUPPLIER).append(" ")
                .append(ClientProxyShape.FIELD_DELEGATE).append(";\n\n");

        // No-arg constructor calling the simplest non-private super constructor with default values
        // (null / 0 / false) — the proxy never uses the super state, it forwards to the delegate.
        // Mirrors the runtime front-end's findSimplestConstructor + the emitter's pushDefault, so
        // beans with only an injected (arg-bearing) constructor are still proxyable in-module.
        sb.append("    public ").append(proxySimple).append("() { super(")
                .append(superDefaultArgs(shape.superCtorParams())).append("); }\n\n");

        // Setter.
        sb.append("    public void ").append(ClientProxyShape.SET_DELEGATE_METHOD)
                .append("(").append(SUPPLIER).append(" d) { this.")
                .append(ClientProxyShape.FIELD_DELEGATE).append(" = d; }\n\n");

        // Forwarding overrides.
        for (ProxyMethodShape m : shape.methods()) {
            renderForward(sb, beanSource, m);
        }

        sb.append("}\n");
        return new Generated(proxyBinary, sb.toString());
    }

    /**
     * Renders the {@code super(...)} argument list calling the chosen constructor with default
     * values: an empty string for a no-arg ctor, else {@code (T0) null, 0, false, …} matching its
     * (erased) parameter types. Each reference default is cast so the call resolves unambiguously.
     */
    private static String superDefaultArgs(List<TypeRef> params) {
        var sb = new StringBuilder();
        for (int i = 0; i < params.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(defaultValueExpr(params.get(i)));
        }
        return sb.toString();
    }

    /** Default-value expression for a super-ctor argument: typed primitive zero, or {@code (T) null}. */
    private static String defaultValueExpr(TypeRef t) {
        if (!t.isPrimitive()) {
            return "(" + t.sourceName() + ") null";
        }
        return switch (t.primitiveKind()) {
            case BOOLEAN -> "false";
            case BYTE    -> "(byte) 0";
            case SHORT   -> "(short) 0";
            case INT     -> "0";
            case LONG    -> "0L";
            case CHAR    -> "(char) 0";
            case FLOAT   -> "0.0f";
            case DOUBLE  -> "0.0";
            default      -> "0";
        };
    }

    static void renderForward(StringBuilder sb, String beanSource, ProxyMethodShape m) {
        boolean isVoid = m.returnType().isVoid();
        List<TypeRef> params = m.params();

        sb.append("    @Override\n");
        sb.append("    public ").append(m.returnType().sourceName()).append(" ")
                .append(m.name()).append("(");
        for (int i = 0; i < params.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(params.get(i).sourceName()).append(" p").append(i);
        }
        sb.append(")");
        // Keep the bean method's (erased) checked-exception contract so the forwarding call compiles.
        var thrown = m.thrownTypes();
        if (!thrown.isEmpty()) {
            sb.append(" throws ");
            for (int i = 0; i < thrown.size(); i++) {
                if (i > 0) sb.append(", ");
                sb.append(thrown.get(i).sourceName());
            }
        }
        sb.append(" {\n");
        // A shadowed default method goes through its interface: a call typed by the bean class
        // resolves to the shadowing private method and is refused (BUG-20261004-08). The interface
        // may be generic, so its result is cast back to the type this override declares.
        var owner = m.interfaceOwner();
        sb.append("        ").append(isVoid ? "" : "return ");
        if (owner != null && !isVoid) {
            sb.append("(").append(m.returnType().sourceName()).append(") ");
        }
        sb.append("((").append(owner != null ? owner.sourceName() : beanSource).append(") ")
                .append(ClientProxyShape.FIELD_DELEGATE).append(".get()).").append(m.name()).append("(");
        for (int i = 0; i < params.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append("p").append(i);
        }
        sb.append(");\n");
        sb.append("    }\n\n");
    }
}
