/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.vauban.processor.codegen.proxy;

import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.ArrayType;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.ElementFilter;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;
import java.util.List;

/**
 * Renders the {@code <Bean>_ClientProxy} normal-scoped client proxy as readable Java
 * <strong>source</strong> — the APT counterpart of the bytecode {@link ClientProxyGenerator}.
 *
 * <p>Emitting source (instead of Filer bytecode) lets the sibling generated source
 * {@code _VaubanComponents} reference {@code <Bean>_ClientProxy} by name and perform
 * {@code new <Bean>_ClientProxy()} in-module — so the container creates the proxy without reflection
 * and the bean package needs no {@code opens}/{@code exports}. This dissolves the same
 * "generated source cannot see Filer-emitted bytecode" wall that moved {@code $$Intercepted} to
 * source. The bytecode {@link ClientProxyGenerator} is kept for the runtime classpath fallback and
 * the Maven plugin (post-compile, external jars).
 *
 * <p>Only generated for top-level normal-scoped beans with an accessible no-arg constructor (the
 * proxy constructor is {@code super()}); other beans keep the bytecode proxy + runtime fallback —
 * see the caller in {@code VaubanProcessor}.
 *
 * <p>The override set mirrors the bytecode generator: <em>declared</em>, non-static, non-private,
 * non-final, non-abstract instance methods, in <em>erased</em> signatures (a valid override of the
 * bean method's erasure — the proven {@code $$Intercepted} approach). Each override forwards the call
 * to the contextual instance: {@code return ((Bean) $$delegate.get()).method(args);}.
 */
public final class ClientProxySourceRenderer {

    private static final String SUPPLIER = "java.util.function.Supplier";

    private ClientProxySourceRenderer() {}

    /** A generated source file: its fully-qualified class name and its textual content. */
    public record Generated(String className, String source) {}

    /** Render {@code <Bean>_ClientProxy} as Java source from the bean's {@link TypeElement}. */
    public static Generated render(TypeElement bean, Elements elements, Types types) {
        String beanBinary = elements.getBinaryName(bean).toString();
        String beanSource = beanBinary.replace('$', '.');
        String proxyBinary = beanBinary + "_ClientProxy";
        int lastDot = beanBinary.lastIndexOf('.');
        String pkg = lastDot >= 0 ? beanBinary.substring(0, lastDot) : "";
        String proxySimple = (lastDot >= 0 ? beanBinary.substring(lastDot + 1) : beanBinary) + "_ClientProxy";

        var sb = new StringBuilder();
        if (!pkg.isEmpty()) {
            sb.append("package ").append(pkg).append(";\n\n");
        }
        sb.append("// Generated by Vauban APT — normal-scoped client proxy of ").append(beanSource)
                .append(".\n");
        sb.append("// Forwards every business method to the contextual instance. Do not edit.\n");
        // @Vetoed: the proxy is instantiated explicitly, never discovered as a bean.
        sb.append("@jakarta.enterprise.inject.Vetoed\n");
        sb.append("@SuppressWarnings({\"unchecked\", \"rawtypes\"})\n");
        sb.append("public final class ").append(proxySimple).append(" extends ").append(beanSource)
                .append(" {\n\n");

        // Delegate supplier — set lazily via $$setDelegate (aligned with RuntimeClientProxyGenerator).
        sb.append("    private ").append(SUPPLIER).append(" $$delegate;\n\n");

        // No-arg constructor calling the simplest non-private super constructor with default values
        // (null / 0 / false) — the proxy never uses the super state, it forwards to the delegate.
        // Mirrors RuntimeClientProxyGenerator.findSimplestConstructor + pushDefault, so beans with
        // only an injected (arg-bearing) constructor are still proxyable in-module. The caller gates
        // on the presence of a non-private constructor.
        sb.append("    public ").append(proxySimple).append("() { super(")
                .append(superDefaultArgs(bean, elements, types)).append("); }\n\n");

        // Setter.
        sb.append("    public void $$setDelegate(").append(SUPPLIER).append(" d) { this.$$delegate = d; }\n\n");

        // Forwarding overrides (declared methods only, mirroring the bytecode generator).
        for (ExecutableElement m : ElementFilter.methodsIn(bean.getEnclosedElements())) {
            if (!shouldProxy(m)) continue;
            renderForward(sb, beanSource, m, elements, types);
        }

        sb.append("}\n");
        return new Generated(proxyBinary, sb.toString());
    }

    /**
     * Renders the {@code super(...)} argument list calling the simplest non-private constructor with
     * default values: an empty string for a no-arg ctor (or no declared ctor), else
     * {@code (T0) null, 0, false, …} matching the chosen ctor's (erased) parameter types. Each
     * reference default is cast so the call resolves unambiguously to the chosen constructor.
     */
    private static String superDefaultArgs(TypeElement bean, Elements elements, Types types) {
        ExecutableElement simplest = null;
        for (ExecutableElement c : ElementFilter.constructorsIn(bean.getEnclosedElements())) {
            if (c.getModifiers().contains(Modifier.PRIVATE)) continue;
            if (simplest == null || c.getParameters().size() < simplest.getParameters().size()) {
                simplest = c;
            }
        }
        if (simplest == null || simplest.getParameters().isEmpty()) {
            return ""; // implicit/declared no-arg ctor -> super()
        }
        var sb = new StringBuilder();
        var params = simplest.getParameters();
        for (int i = 0; i < params.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(defaultValueExpr(params.get(i).asType(), elements, types));
        }
        return sb.toString();
    }

    /** Default-value expression for a super-ctor argument: typed primitive zero, or {@code (T) null}. */
    private static String defaultValueExpr(TypeMirror t, Elements elements, Types types) {
        return switch (t.getKind()) {
            case BOOLEAN -> "false";
            case BYTE    -> "(byte) 0";
            case SHORT   -> "(short) 0";
            case INT     -> "0";
            case LONG    -> "0L";
            case CHAR    -> "(char) 0";
            case FLOAT   -> "0.0f";
            case DOUBLE  -> "0.0";
            default      -> "(" + sourceName(t, elements, types) + ") null";
        };
    }

    /** Mirrors {@code ClientProxyGenerator.shouldProxy}: skip ctor/static/private/final/abstract/{@code $$}. */
    private static boolean shouldProxy(ExecutableElement m) {
        var mods = m.getModifiers();
        if (mods.contains(Modifier.STATIC)) return false;
        if (mods.contains(Modifier.PRIVATE)) return false;
        if (mods.contains(Modifier.FINAL)) return false;
        if (mods.contains(Modifier.ABSTRACT)) return false;
        return !m.getSimpleName().toString().startsWith("$$");
    }

    private static void renderForward(StringBuilder sb, String beanSource, ExecutableElement m,
            Elements elements, Types types) {
        String name = m.getSimpleName().toString();
        boolean isVoid = m.getReturnType().getKind() == TypeKind.VOID;
        List<? extends VariableElement> params = m.getParameters();

        sb.append("    @Override\n");
        sb.append("    public ").append(sourceName(m.getReturnType(), elements, types)).append(" ")
                .append(name).append("(");
        for (int i = 0; i < params.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(sourceName(params.get(i).asType(), elements, types)).append(" p").append(i);
        }
        sb.append(")");
        // Keep the bean method's (erased) checked-exception contract so the forwarding call compiles.
        var thrown = m.getThrownTypes();
        if (!thrown.isEmpty()) {
            sb.append(" throws ");
            for (int i = 0; i < thrown.size(); i++) {
                if (i > 0) sb.append(", ");
                sb.append(sourceName(thrown.get(i), elements, types));
            }
        }
        sb.append(" {\n");
        sb.append("        ").append(isVoid ? "" : "return ")
                .append("((").append(beanSource).append(") $$delegate.get()).").append(name).append("(");
        for (int i = 0; i < params.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append("p").append(i);
        }
        sb.append(");\n");
        sb.append("    }\n\n");
    }

    /** Erased Java source type name: {@code int}, {@code java.lang.String}, {@code int[]}, {@code a.b.Outer.Inner}. */
    private static String sourceName(TypeMirror tm, Elements elements, Types types) {
        return sourceName(tm, elements, types, 0);
    }

    private static String sourceName(TypeMirror tm, Elements elements, Types types, int dims) {
        return switch (tm.getKind()) {
            case VOID    -> "void";
            case BOOLEAN -> withDims("boolean", dims);
            case BYTE    -> withDims("byte", dims);
            case CHAR    -> withDims("char", dims);
            case SHORT   -> withDims("short", dims);
            case INT     -> withDims("int", dims);
            case LONG    -> withDims("long", dims);
            case FLOAT   -> withDims("float", dims);
            case DOUBLE  -> withDims("double", dims);
            case ARRAY   -> sourceName(((ArrayType) tm).getComponentType(), elements, types, dims + 1);
            default      -> {
                // Declared, type-var, wildcard, intersection — erase to a nameable reference type.
                TypeMirror erased = types.erasure(tm);
                if (erased instanceof DeclaredType dt) {
                    yield withDims(elements.getBinaryName((TypeElement) dt.asElement()).toString()
                            .replace('$', '.'), dims);
                }
                yield withDims("java.lang.Object", dims);
            }
        };
    }

    private static String withDims(String base, int dims) {
        return dims == 0 ? base : base + "[]".repeat(dims);
    }
}
