/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.vauban.processor.codegen.proxy;

import io.vidocq.vauban.core.proxy.ClientProxyShape.ProxyMethodShape;
import io.vidocq.vauban.processor.codegen.interceptor.InterceptedShapeFromElements;

import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.util.ElementFilter;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

/**
 * Renders a build-time client proxy for a normal-scoped producer whose produced type is an
 * <strong>interface</strong> (issue #42). Instead of a runtime {@code java.lang.reflect.Proxy}, the
 * APT emits a static class {@code implements <Iface>} in the producer's own package that forwards
 * every method — abstract <em>and</em> {@code default} — to the contextual instance. Zero runtime
 * reflection, zero dynamic proxy. The source counterpart of the class-typed
 * {@link ClientProxySourceRenderer}, but implementing the interface rather than extending a class
 * (interfaces have no constructor to chain).
 */
public final class InterfaceProxySourceRenderer {

    private static final String SUPPLIER = "java.util.function.Supplier";

    private InterfaceProxySourceRenderer() {}

    /** Render the interface proxy at {@code proxyBinaryName}, implementing {@code iface}. */
    public static ClientProxySourceRenderer.Generated render(
            TypeElement iface, String proxyBinaryName, Elements elements, Types types) {
        String ifaceSource = elements.getBinaryName(iface).toString().replace('$', '.');
        int lastDot = proxyBinaryName.lastIndexOf('.');
        String pkg = lastDot >= 0 ? proxyBinaryName.substring(0, lastDot) : "";
        String proxySimple = lastDot >= 0 ? proxyBinaryName.substring(lastDot + 1) : proxyBinaryName;

        var sb = new StringBuilder();
        if (!pkg.isEmpty()) {
            sb.append("package ").append(pkg).append(";\n\n");
        }
        sb.append("// Generated by Vauban APT — normal-scoped client proxy of interface ")
                .append(ifaceSource).append(".\n");
        sb.append("// Forwards every method (abstract and default) to the contextual instance. Do not edit.\n");
        sb.append("@jakarta.enterprise.inject.Vetoed\n");
        sb.append("@SuppressWarnings({\"unchecked\", \"rawtypes\"})\n");
        sb.append("public final class ").append(proxySimple).append(" implements ")
                .append(ifaceSource).append(" {\n\n");
        sb.append("    private ").append(SUPPLIER).append(" $$delegate;\n\n");
        sb.append("    public ").append(proxySimple).append("() {}\n\n");
        sb.append("    public void $$setDelegate(").append(SUPPLIER)
                .append(" d) { this.$$delegate = d; }\n\n");

        for (ProxyMethodShape m : collectMethods(iface, elements, types)) {
            ClientProxySourceRenderer.renderForward(sb, ifaceSource, m);
        }

        sb.append("}\n");
        return new ClientProxySourceRenderer.Generated(proxyBinaryName, sb.toString());
    }

    /**
     * Every instance method a client can call on the interface — declared or inherited from a
     * super-interface, abstract or {@code default} — excluding {@code static}/{@code private}
     * members and the implicit {@code java.lang.Object} methods (which the proxy inherits from
     * {@code Object}, exactly as a {@code reflect.Proxy} keeps its own equals/hashCode/toString).
     */
    private static List<ProxyMethodShape> collectMethods(TypeElement iface, Elements elements, Types types) {
        var methods = new ArrayList<ProxyMethodShape>();
        var seen = new HashSet<String>();
        for (ExecutableElement m : ElementFilter.methodsIn(elements.getAllMembers(iface))) {
            var mods = m.getModifiers();
            if (mods.contains(Modifier.STATIC) || mods.contains(Modifier.PRIVATE)) {
                continue;
            }
            if (m.getEnclosingElement() instanceof TypeElement te
                    && te.getQualifiedName().contentEquals("java.lang.Object")) {
                continue;
            }
            var params = m.getParameters().stream()
                    .map(p -> InterceptedShapeFromElements.typeRefOf(p.asType(), elements, types, 0))
                    .toList();
            var key = m.getSimpleName() + "|" + params.stream()
                    .map(io.vidocq.vauban.core.interceptor.TypeRef::sourceName)
                    .reduce("", (a, b) -> a + "," + b);
            if (!seen.add(key)) {
                continue;
            }
            methods.add(new ProxyMethodShape(
                    m.getSimpleName().toString(),
                    InterceptedShapeFromElements.typeRefOf(m.getReturnType(), elements, types, 0),
                    params,
                    m.getThrownTypes().stream()
                            .map(t -> InterceptedShapeFromElements.typeRefOf(t, elements, types, 0)).toList(),
                    false));
        }
        return methods;
    }
}
