package fr.vidocq.example.app;

import fr.vidocq.vauban.core.container.VaubanContainer;

/**
 * Entry point for the Vauban CDI example application.
 *
 * <p>Demonstrates:
 * <ul>
 *   <li>{@code scanClasspath()} — loads ALL beans (local + dependencies) from
 *       {@code META-INF/vauban-beans.list} generated by {@code vauban-maven-plugin}</li>
 *   <li>Cross-JAR injection — WelcomeService injects GreetingService from example-lib</li>
 * </ul>
 *
 * <p>Note: when using vauban-maven-plugin, {@code scanClasspath()} alone is sufficient
 * because the plugin lists both local and dependency beans in the beans list.
 * {@code scanLocal()} is for use without the plugin.
 */
public class Main {

    public static void main(String[] args) {
        // Boot the CDI container
        try (var container = VaubanContainer.builder()
                .scanClasspath()    // loads beans from vauban-beans.list (deps + local)
                .build()) {

            // Get the application bean (which injects beans from example-lib)
            var welcomeService = container.select(WelcomeService.class);

            // Use it
            var name = args.length > 0 ? args[0] : "Vauban";
            System.out.println(welcomeService.welcome(name));
        }
    }
}
