/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.vauban.processor.codegen.interceptor;

import io.vidocq.vauban.core.interceptor.CtorShape;
import io.vidocq.vauban.core.interceptor.InterceptedShape;
import io.vidocq.vauban.core.interceptor.MethodShape;
import io.vidocq.vauban.core.interceptor.TypeRef;

import java.util.List;

/**
 * Renders the {@code <bean>$$Intercepted} subclass as readable Java <strong>source</strong> from a
 * neutral {@link InterceptedShape} — the APT counterpart of the bytecode
 * {@link io.vidocq.vauban.core.interceptor.InterceptedEmitter}.
 *
 * <p>The two share the same {@link InterceptedShape} (built by {@link InterceptedShapeFromElements}),
 * so the override set is identical; only the rendering differs. Emitting source lets a sibling
 * generated source — the {@code _VaubanComponents} provider — reference {@code <bean>$$Intercepted}
 * by name (javac resolves it in a later round), which dissolves the "generated source cannot see
 * generated bytecode" wall that forced the provider to be emitted as bytecode. The bytecode emitter
 * is kept for the runtime classpath fallback and the Maven plugin (post-compile, external jars).
 *
 * <p>Generated shape, per interceptable method {@code work}:
 * <ul>
 *   <li>the override {@code work()} — builds the {@code VaubanInvocationContext}, resolves the chain
 *       at run time and drives it; a pre-init guard ({@code $$manager == null}) calls {@code super}
 *       directly during construction;</li>
 *   <li>a bridge {@code $$super$work()} — {@code return super.work(...)}, the only way to reach the
 *       original body without re-entering interception;</li>
 *   <li>a static glue {@code $$ti$work(Object, Object[])} lifted to a {@code TargetInvoker} by a
 *       method reference — javac emits the same {@code invokedynamic}/{@code LambdaMetafactory} the
 *       bytecode emitter hand-rolls.</li>
 * </ul>
 *
 * <p><strong>Checked exceptions.</strong> {@link MethodShape} carries no {@code throws} clause and
 * {@code VaubanInvocationContext.proceed()} is {@code throws Exception}, while the override must keep
 * the (narrow-or-none) throws of the bean method. The override therefore catches every
 * {@link Throwable} and re-throws the <em>real</em> one through a generic-erasure {@code sneaky}
 * helper — bytecode-faithful (the JVM never checks checked exceptions) and identity-preserving.
 */
public final class InterceptedSourceRenderer {

    private static final String IM = "io.vidocq.vauban.core.interceptor.InterceptorManager";
    private static final String CTX = "io.vidocq.vauban.core.interceptor.VaubanInvocationContext";
    private static final String CREATIONAL = "jakarta.enterprise.context.spi.CreationalContext";

    private InterceptedSourceRenderer() {}

    /** A generated source file: its fully-qualified class name and its textual content. */
    public record Generated(String className, String source) {}

    /** Render {@code shape.subclassName()} as Java source. */
    public static Generated render(InterceptedShape shape) {
        String beanBinary = shape.beanBinaryName();
        String subBinary = shape.subclassName();
        int lastDot = beanBinary.lastIndexOf('.');
        String pkg = lastDot >= 0 ? beanBinary.substring(0, lastDot) : "";
        String beanSimple = lastDot >= 0 ? beanBinary.substring(lastDot + 1) : beanBinary;
        String subSimple = beanSimple + InterceptedShape.SUBCLASS_SUFFIX;
        String beanSource = beanBinary.replace('$', '.');

        var sb = new StringBuilder();
        if (!pkg.isEmpty()) {
            sb.append("package ").append(pkg).append(";\n\n");
        }
        sb.append("// Generated by Vauban APT — intercepted subclass of ").append(beanSource)
                .append(". Drives the\n");
        sb.append("// deployment-dynamic interceptor chain at run time. Do not edit.\n");
        sb.append("@SuppressWarnings({\"unchecked\", \"rawtypes\"})\n");
        sb.append("public class ").append(subSimple).append(" extends ").append(beanSource).append(" {\n\n");

        // Fields — names come from the shared IR (single authority with the bytecode emitter)
        sb.append("    private ").append(IM).append(" ").append(InterceptedShape.FIELD_MANAGER).append(";\n");
        sb.append("    private java.util.Set ").append(InterceptedShape.FIELD_BINDINGS).append(";\n");
        sb.append("    private java.util.Set ").append(InterceptedShape.FIELD_CONSTRUCTOR_BINDINGS).append(";\n");
        sb.append("    private ").append(CREATIONAL).append(" ").append(InterceptedShape.FIELD_CONTEXT).append(";\n\n");

        // Constructors mirroring each non-private super constructor
        for (CtorShape ctor : shape.constructors()) {
            sb.append("    public ").append(subSimple).append("(").append(params(ctor.params())).append(") {\n");
            sb.append("        super(").append(args(ctor.params().size())).append(");\n");
            sb.append("    }\n\n");
        }

        // $$init setter
        sb.append("    public void ").append(InterceptedShape.INIT_METHOD)
                .append("(").append(IM).append(" m, java.util.Set b, ")
                .append("java.util.Set cb, ").append(CREATIONAL).append(" c) {\n");
        sb.append("        this.$$manager = m;\n");
        sb.append("        this.$$bindings = b;\n");
        sb.append("        this.$$constructorBindings = cb;\n");
        sb.append("        this.$$context = c;\n");
        sb.append("    }\n\n");

        // The $$ti$ glue erases to (Object, Object[]) Object, so two overloaded methods would
        // collide on the bare $$ti$<name>; give each overload a unique name (the $$super$<name>
        // bridges keep distinct parameter lists and need no suffix).
        var methods = shape.methods();
        var tiNames = shape.targetInvokerNames();
        for (int i = 0; i < methods.size(); i++) {
            MethodShape m = methods.get(i);
            renderOverride(sb, subSimple, m, tiNames.get(i));
            renderSuperBridge(sb, m);
            renderTargetInvokerGlue(sb, subSimple, m, tiNames.get(i));
        }

        // Sneaky-throw: T appears only in `throws T`, so by JLS §18.4 it resolves to
        // RuntimeException at every call site — the override needs no checked-throws clause, yet the
        // original throwable propagates unwrapped (erasure casts to Throwable, not RuntimeException).
        sb.append("    @SuppressWarnings(\"unchecked\")\n");
        sb.append("    private static <T extends Throwable> RuntimeException sneaky(Throwable t) throws T {\n");
        sb.append("        throw (T) t;\n");
        sb.append("    }\n");

        sb.append("}\n");
        return new Generated(subBinary, sb.toString());
    }

    private static void renderOverride(StringBuilder sb, String subSimple, MethodShape m, String tiName) {
        TypeRef ret = m.returnType();
        String retType = sourceName(ret);
        sb.append("    @Override\n");
        sb.append("    public ").append(retType).append(" ").append(m.name())
                .append("(").append(params(m.params())).append(") {\n");

        sb.append("        try {\n");
        // Pre-init guard: during construction the container has not called $$init yet. It lives
        // INSIDE the try so that a checked exception thrown by the original method propagates through
        // sneaky() — the override drops the `throws` clause (MethodShape carries no throws), so a bare
        // `super.<m>(...)` here would otherwise be an unreported checked exception. sneaky() rethrows
        // the very same throwable, so the behaviour matches the bytecode emitter (which has no checked
        // enforcement).
        if (ret.isVoid()) {
            sb.append("            if (this.$$manager == null) { super.").append(m.name())
                    .append("(").append(args(m.params().size())).append("); return; }\n");
        } else {
            sb.append("            if (this.$$manager == null) return super.").append(m.name())
                    .append("(").append(args(m.params().size())).append(");\n");
        }
        sb.append("            java.lang.reflect.Method $$m = getClass().getDeclaredMethod(\"")
                .append(InterceptedShape.superBridgeName(m.name())).append("\"")
                .append(classLiterals(m.params())).append(");\n");
        sb.append("            Object[] $$args = new Object[] {").append(boxedArgs(m.params())).append("};\n");
        sb.append("            java.util.List $$chain = this.$$manager.resolveChainForMethod(")
                .append("this.$$bindings, $$m, this, this.$$context);\n");
        sb.append("            ").append(CTX).append(" $$ctx = new ").append(CTX)
                .append("(this, $$m, null, $$args, $$chain, ").append(subSimple).append("::")
                .append(tiName).append(");\n");
        if (ret.isVoid()) {
            sb.append("            $$ctx.proceed();\n");
            sb.append("            this.$$manager.shareInstances(").append(IM)
                    .append(".$$getAroundConstructContext());\n");
            sb.append("            return;\n");
        } else {
            sb.append("            Object $$r = $$ctx.proceed();\n");
            sb.append("            this.$$manager.shareInstances(").append(IM)
                    .append(".$$getAroundConstructContext());\n");
            sb.append("            return ").append(unboxExpr(ret, "$$r")).append(";\n");
        }
        sb.append("        } catch (Throwable $$t) {\n");
        sb.append("            throw sneaky($$t);\n");
        sb.append("        }\n");
        sb.append("    }\n\n");
    }

    private static void renderSuperBridge(StringBuilder sb, MethodShape m) {
        TypeRef ret = m.returnType();
        sb.append("    public ").append(sourceName(ret)).append(" ")
                .append(InterceptedShape.superBridgeName(m.name()))
                .append("(").append(params(m.params())).append(") throws Exception {\n");
        if (ret.isVoid()) {
            sb.append("        super.").append(m.name()).append("(").append(args(m.params().size())).append(");\n");
        } else {
            sb.append("        return super.").append(m.name()).append("(").append(args(m.params().size())).append(");\n");
        }
        sb.append("    }\n\n");
    }

    private static void renderTargetInvokerGlue(StringBuilder sb, String subSimple, MethodShape m, String tiName) {
        TypeRef ret = m.returnType();
        var unboxed = new StringBuilder();
        var params = m.params();
        for (int i = 0; i < params.size(); i++) {
            if (i > 0) unboxed.append(", ");
            unboxed.append(unboxExpr(params.get(i), "$$params[" + i + "]"));
        }
        String call = "((" + subSimple + ") $$target)." + InterceptedShape.superBridgeName(m.name())
                + "(" + unboxed + ")";

        sb.append("    private static Object ").append(tiName)
                .append("(Object $$target, Object[] $$params) throws Exception {\n");
        if (ret.isVoid()) {
            sb.append("        ").append(call).append(";\n");
            sb.append("        return null;\n");
        } else if (ret.isPrimitive()) {
            sb.append("        return ").append(wrapper(ret)).append(".valueOf(").append(call).append(");\n");
        } else {
            sb.append("        return ").append(call).append(";\n");
        }
        sb.append("    }\n\n");
    }

    // ---- rendering helpers ----

    /** Parameter declaration list: {@code <type> p0, <type> p1, …}. */
    private static String params(List<TypeRef> params) {
        var sb = new StringBuilder();
        for (int i = 0; i < params.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(sourceName(params.get(i))).append(" p").append(i);
        }
        return sb.toString();
    }

    /** Argument pass-through list: {@code p0, p1, …}. */
    private static String args(int count) {
        var sb = new StringBuilder();
        for (int i = 0; i < count; i++) {
            if (i > 0) sb.append(", ");
            sb.append("p").append(i);
        }
        return sb.toString();
    }

    /** Boxed argument list for {@code Object[]}: {@code Integer.valueOf(p0), p1, …}. */
    private static String boxedArgs(List<TypeRef> params) {
        var sb = new StringBuilder();
        for (int i = 0; i < params.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(boxExpr(params.get(i), "p" + i));
        }
        return sb.toString();
    }

    /** Trailing {@code .class} literals for {@code getDeclaredMethod}: {@code , int.class, String.class}. */
    private static String classLiterals(List<TypeRef> params) {
        var sb = new StringBuilder();
        for (TypeRef p : params) {
            sb.append(", ").append(sourceName(p)).append(".class");
        }
        return sb.toString();
    }

    private static String boxExpr(TypeRef t, String var) {
        if (t.isPrimitive()) {
            return wrapper(t) + ".valueOf(" + var + ")";
        }
        return var;
    }

    private static String unboxExpr(TypeRef t, String objExpr) {
        if (t.isPrimitive()) {
            return "((" + wrapper(t) + ") " + objExpr + ")." + primitiveAccessor(t) + "()";
        }
        if (t.binaryName() != null && t.binaryName().equals("java.lang.Object") && t.dims() == 0) {
            return objExpr;
        }
        return "(" + sourceName(t) + ") " + objExpr;
    }

    /** Java source type name — delegates to the shared IR ({@link TypeRef#sourceName()}). */
    private static String sourceName(TypeRef t) {
        return t.sourceName();
    }

    /** Wrapper binary name — single authority is {@link TypeRef#wrapperBinaryName()}. */
    private static String wrapper(TypeRef t) {
        return t.wrapperBinaryName();
    }

    /** Unbox accessor — single authority is {@link TypeRef#unboxAccessorName()}. */
    private static String primitiveAccessor(TypeRef t) {
        return t.unboxAccessorName();
    }
}
