<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.1.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.1.0</modelVersion>

    <parent>
        <groupId>fr.vidocq.vauban</groupId>
        <artifactId>vauban-parent</artifactId>
    </parent>

    <artifactId>vauban-processor</artifactId>
    <name>Vauban :: Processor</name>
    <description>Annotation processor and bytecode generation</description>

    <dependencies>
        <dependency>
            <groupId>fr.vidocq.vauban</groupId>
            <artifactId>vauban-core</artifactId>
        </dependency>
        <dependency>
            <groupId>fr.vidocq.vauban</groupId>
            <artifactId>vauban-indexer</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
