/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.vauban.processor.codegen.factory;

import javax.lang.model.element.TypeElement;

/**
 * Renders the {@code <Bean>_Factory} as Java <strong>source</strong> instead of
 * Filer bytecode (workspace APT-first rule, codegen audit CG-02). javac emits the
 * {@code Object create()} bridge itself, so the rendered class is the minimal
 * mirror of what {@link BeanFactoryGenerator} produced in bytecode.
 *
 * <p>Used only when the compilation environment can resolve
 * {@code io.vidocq.vauban.core.BeanFactory} (the generated source must compile in
 * the user's module, unlike bytecode whose references resolve at load time) and the
 * bean is a top-level type with an accessible no-arg constructor;
 * {@link BeanFactoryGenerator} remains the documented bytecode fallback for every
 * other case.</p>
 */
public final class BeanFactorySourceRenderer {

    private BeanFactorySourceRenderer() {
    }

    /** Generated source artifact: fully-qualified class name + textual content. */
    public record Generated(String className, String source) {
    }

    public static Generated render(TypeElement bean) {
        String beanFqn = bean.getQualifiedName().toString();
        int lastDot = beanFqn.lastIndexOf('.');
        String packageName = lastDot < 0 ? "" : beanFqn.substring(0, lastDot);
        String simpleName = bean.getSimpleName().toString();
        String factorySimple = simpleName + "_Factory";
        String factoryFqn = beanFqn + "_Factory";

        StringBuilder out = new StringBuilder(512);
        if (!packageName.isEmpty()) {
            out.append("package ").append(packageName).append(";\n\n");
        }
        out.append("// Generated by io.vidocq.vauban.processor.VaubanProcessor — do not edit.\n");
        out.append("public final class ").append(factorySimple)
                .append(" implements io.vidocq.vauban.core.BeanFactory<").append(beanFqn).append("> {\n\n");
        out.append("    public ").append(factorySimple).append("() {\n    }\n\n");
        out.append("    @java.lang.Override\n");
        out.append("    public ").append(beanFqn).append(" create() {\n");
        out.append("        return new ").append(beanFqn).append("();\n");
        out.append("    }\n");
        out.append("}\n");
        return new Generated(factoryFqn, out.toString());
    }
}
