package io.vidocq.vauban.maven.generate;

import io.vidocq.vauban.core.bean.discovery.BeanDiscovery;
import io.vidocq.vauban.core.bean.model.BeanDescriptor;
import io.vidocq.vauban.core.bean.model.BeanDescriptor.BeanKind;
import io.vidocq.vauban.core.interceptor.InterceptorSubclassGenerator;
import io.vidocq.vauban.core.proxy.RuntimeClientProxyGenerator;
import io.vidocq.vauban.indexer.IndexBuilder;
import io.vidocq.vauban.indexer.scanner.ClassFileScanner;
import io.vidocq.vauban.indexer.scanner.JarScanner;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.*;
import java.util.jar.JarFile;

/**
 * Core build-time logic for CDI bean discovery and code generation.
 * <p>
 * Scans dependency JARs and project classes, runs CDI bean discovery,
 * pre-generates client proxies and interceptor subclasses, and writes
 * a {@code META-INF/vauban-beans.list} file for runtime discovery.
 * <p>
 * Avoids double processing: JARs or project classes that already contain
 * a {@code vauban-beans.list} (e.g. generated by APT) are not re-discovered.
 * Proxy classes already present on disk are not regenerated.
 * <p>
 * This class has no Maven dependency and is independently testable.
 */
public final class VaubanGenerator {

    /** Location of the bean list file within the classpath. */
    public static final String BEANS_LIST_PATH = "META-INF/vauban-beans.list";


    /** Suffixes of classes generated by Vauban — excluded from index scanning. */
    private static final List<String> GENERATED_SUFFIXES = List.of(
            "_ClientProxy", "_Factory", "$$Intercepted"
    );

    /**
     * Configuration for the generator.
     *
     * @param dependencyJars    JAR files to scan for CDI beans
     * @param projectClassesDir project's compiled classes directory (may be null)
     * @param outputDir         where to write generated files
     * @param classLoader       ClassLoader with all deps + project classes for proxy generation (may be null to skip generation)
     */
    public record Config(
            List<Path> dependencyJars,
            Path projectClassesDir,
            Path outputDir,
            ClassLoader classLoader
    ) {
        public Config {
            dependencyJars = List.copyOf(dependencyJars);
        }

        /** Config without ClassLoader — discovery only, no proxy generation. */
        public Config(List<Path> dependencyJars, Path projectClassesDir, Path outputDir) {
            this(dependencyJars, projectClassesDir, outputDir, null);
        }
    }

    private VaubanGenerator() {}

    /**
     * Scan dependencies and project classes, discover CDI beans,
     * generate proxies/interceptor subclasses, and write the bean list file.
     * <p>
     * Already-processed sources (containing {@code vauban-beans.list}) are not
     * re-discovered. Their bean names are collected and merged into the final list.
     * Proxy/interceptor classes already on disk are not regenerated.
     *
     * @param config generation configuration
     * @return result with discovered beans, generated classes, and warnings
     * @throws IOException if scanning or writing fails
     */
    public static GenerationResult generate(Config config) throws IOException {
        var indexBuilder = new IndexBuilder();
        var warnings = new ArrayList<String>();
        var alreadyKnownBeans = new LinkedHashSet<String>();

        // 1. Scan dependency JARs
        for (var dep : config.dependencyJars()) {
            if (Files.isDirectory(dep)) {
                // Reactor dependency — check for existing beans list
                var existingBeans = readBeansListFromDirectory(dep);
                if (!existingBeans.isEmpty()) {
                    alreadyKnownBeans.addAll(existingBeans);
                } else {
                    scanClassesDirectory(dep, indexBuilder, warnings);
                }
            } else if (Files.isRegularFile(dep)) {
                // JAR dependency — check for existing beans list
                var existingBeans = readBeansListFromJar(dep);
                if (!existingBeans.isEmpty()) {
                    alreadyKnownBeans.addAll(existingBeans);
                } else {
                    try {
                        var classInfos = JarScanner.scan(dep);
                        indexBuilder.addAll(classInfos);
                    } catch (IOException e) {
                        warnings.add("Failed to scan JAR " + dep.getFileName() + ": " + e.getMessage());
                    }
                }
            } else {
                warnings.add("Skipping non-existent dependency: " + dep);
            }
        }

        // 2. Scan project classes directory (skip if APT already processed it)
        boolean projectAlreadyProcessed = false;
        if (config.projectClassesDir() != null && Files.isDirectory(config.projectClassesDir())) {
            var existingBeans = readBeansListFromDirectory(config.projectClassesDir());
            if (!existingBeans.isEmpty()) {
                alreadyKnownBeans.addAll(existingBeans);
                projectAlreadyProcessed = true;
                // Still scan project classes for index — needed for interceptor generation
                scanClassesDirectory(config.projectClassesDir(), indexBuilder, warnings);
            } else {
                scanClassesDirectory(config.projectClassesDir(), indexBuilder, warnings);
            }
        }

        // 3. Build merged index
        var index = indexBuilder.build();
        if (index.size() == 0 && alreadyKnownBeans.isEmpty()) {
            return new GenerationResult(List.of(), List.of(), List.of(), warnings);
        }

        // 3b. Run BCE @Enhancement for non-pre-processed classes (if ClassLoader available)
        if (config.classLoader() != null) {
            var bceClasses = discoverBceClasses(config.classLoader());
            if (!bceClasses.isEmpty()) {
                var archiveClasses = loadArchiveClasses(index, config.classLoader());
                var enhMods = io.vidocq.vauban.core.extensions.BceProcessor.processEnhancementOnly(
                        bceClasses, archiveClasses, index, config.classLoader());

                // Brique A for plugin-processed modules (cervantes/cyrano/knock/dirac, which use
                // this plugin instead of the APT): freeze the @Enhancement result as a static
                // patch so the runtime applies it without re-instantiating/replaying the BCE
                // reflectively — removing one reason for `opens … to io.vidocq.vauban.core`.
                writeEnhancementsPatch(config.outputDir(), enhMods, warnings);

                if (!enhMods.isEmpty()) {
                    // Rebuild index with synthetic scope annotations from Enhancement
                    var enrichedBuilder = new IndexBuilder();
                    for (var classInfo : index.getKnownClasses()) {
                        var mods = enhMods.get(classInfo.name());
                        if (mods != null) {
                            var newAnnotations = new java.util.ArrayList<>(classInfo.annotations());
                            for (var mod : mods) {
                                for (var ann : mod.getAddedAnnotations()) {
                                    newAnnotations.add(new io.vidocq.vauban.indexer.model.AnnotationInfo(
                                            io.vidocq.vauban.indexer.model.DotName.of(ann.getName()),
                                            java.util.Map.of()));
                                }
                            }
                            enrichedBuilder.add(new io.vidocq.vauban.indexer.model.ClassInfo(
                                    classInfo.name(), classInfo.superName(), classInfo.interfaces(),
                                    classInfo.accessFlags(), classInfo.fields(), classInfo.methods(),
                                    newAnnotations, classInfo.kind()));
                        } else {
                            enrichedBuilder.add(classInfo);
                        }
                    }
                    index = enrichedBuilder.build();
                }
            }
        }

        // 5. Run CDI bean discovery on enriched index
        var discovery = new BeanDiscovery(index);
        var beans = discovery.discoverBeans();

        // 6. Partition: already-known vs newly-discovered
        var newBeans = new ArrayList<BeanDescriptor>();
        var allBeanClassNames = new LinkedHashSet<>(alreadyKnownBeans);

        for (var bean : beans) {
            var className = bean.beanClass().value();
            allBeanClassNames.add(className);
            if (!alreadyKnownBeans.contains(className)) {
                newBeans.add(bean);
            }
        }

        var sortedBeanClassNames = allBeanClassNames.stream().sorted().toList();

        // 7. Write merged META-INF/vauban-beans.list (only if we have new beans to add)
        if (!newBeans.isEmpty() || !projectAlreadyProcessed) {
            writeBeansList(config.outputDir(), sortedBeanClassNames);
        }

        // 8. Pre-generate proxies and interceptor subclasses (if ClassLoader provided)
        //    Skip classes whose proxy/interceptor already exists on disk
        var generatedProxies = new ArrayList<String>();
        var generatedInterceptors = new ArrayList<String>();

        if (config.classLoader() != null) {
            // For newly discovered beans: generate everything
            // For already-known beans in project: generate interceptors only (APT can't)
            var beansToProcess = projectAlreadyProcessed
                    ? beans  // all beans including project ones (for interceptors)
                    : newBeans;

            for (var bean : beansToProcess) {
                var className = bean.beanClass().value();
                Class<?> clazz;
                try {
                    clazz = Class.forName(className, false, config.classLoader());
                } catch (ClassNotFoundException | NoClassDefFoundError _) {
                    // NoClassDefFoundError: a transitive dependency referenced by this class
                    // is absent from the classpath provided to the plugin (see VAU-MVN-001).
                   warnings.add("Cannot load class for generation: " + className);
                    continue;
                }

                // Client proxy for normal-scoped beans (skip if already exists)
                if (bean.scope().isNormal() && !alreadyKnownBeans.contains(className)) {
                    var proxyClassName = className + "_ClientProxy";
                    if (!classFileExists(config.outputDir(), proxyClassName)) {
                        try {
                            var generated = RuntimeClientProxyGenerator.generate(clazz);
                            writeClassFile(config.outputDir(), generated.className(), generated.bytecode());
                            generatedProxies.add(generated.className());
                        } catch (Exception e) {
                            warnings.add("Failed to generate proxy for " + className + ": " + e.getMessage());
                        }
                    }
                }

                // Interceptor subclass for managed beans with interceptor bindings
                // Always generate if not already on disk (APT does not generate these)
                if (bean.kind() == BeanKind.MANAGED
                        && !bean.interceptorBindings().isEmpty()
                        && !java.lang.reflect.Modifier.isFinal(clazz.getModifiers())) {
                    var interceptorClassName = className + "$$Intercepted";
                    if (!classFileExists(config.outputDir(), interceptorClassName)) {
                        try {
                            var generated = InterceptorSubclassGenerator.generate(clazz);
                            writeClassFile(config.outputDir(), generated.className(), generated.bytecode());
                            generatedInterceptors.add(generated.className());
                        } catch (Exception e) {
                            warnings.add("Failed to generate interceptor subclass for " + className + ": " + e.getMessage());
                        }
                    }
                }
            }
        }

        // 9. Generate the per-module _VaubanComponents provider (bytecode — no javac in the plugin)
        //    for THIS module's public no-arg beans, so the container instantiates them in-module
        //    without reflection and the module can drop `opens … to io.vidocq.vauban.core`.
        generateComponentProvider(config, index, beans, warnings);

        return new GenerationResult(sortedBeanClassNames, generatedProxies, generatedInterceptors, warnings);
    }

    /**
     * Emits one {@code <pkg>/_VaubanComponents.class} <em>per package</em> that has managed beans
     * compiled into this module ({@code projectClassesDir}), plus a class-path service file listing
     * them all. A per-package provider is co-located with its beans, so it can {@code new}/inject/
     * invoke even their <strong>package-private</strong> members without reflection — which a single
     * common-package provider could not reach across packages. Beans from dependency jars are
     * excluded — they carry their own provider. The module still needs a hand-written
     * {@code provides io.vidocq.vauban.api.VaubanComponentProvider with pkgA._VaubanComponents,
     * pkgB._VaubanComponents;} (all providers) for the module path; the class-path service file
     * covers the unnamed-module case.
     */
    private static void generateComponentProvider(Config config,
            io.vidocq.vauban.indexer.VaubanIndex index,
            List<BeanDescriptor> beans, List<String> warnings) {
        var projectDir = config.projectClassesDir();
        if (projectDir == null) return;

        // Per-package accumulators for the three in-module capabilities.
        record Bundle(
                TreeSet<String> noArg,
                List<io.vidocq.vauban.core.provider.ComponentProviderClassGenerator.FieldInject> fields,
                List<io.vidocq.vauban.core.provider.ComponentProviderClassGenerator.MethodInvoke> methods) {}
        var byPackage = new java.util.TreeMap<String, Bundle>();

        var injectName    = io.vidocq.vauban.indexer.model.DotName.of("jakarta.inject.Inject");
        var producesName  = io.vidocq.vauban.indexer.model.DotName.of("jakarta.enterprise.inject.Produces");
        var postConstructName = io.vidocq.vauban.indexer.model.DotName.of("jakarta.annotation.PostConstruct");
        var preDestroyName = io.vidocq.vauban.indexer.model.DotName.of("jakarta.annotation.PreDestroy");
        var observesName  = io.vidocq.vauban.indexer.model.DotName.of("jakarta.enterprise.event.Observes");
        var observesAsyncName = io.vidocq.vauban.indexer.model.DotName.of("jakarta.enterprise.event.ObservesAsync");
        var disposesName  = io.vidocq.vauban.indexer.model.DotName.of("jakarta.enterprise.inject.Disposes");

        for (var bean : beans) {
            if (bean.kind() != BeanKind.MANAGED) continue;
            var fqn = bean.beanClass().value();
            if (fqn.contains("$")) continue;                       // nested → reflective fallback
            if (!classFileExists(projectDir, fqn)) continue;       // not part of this module
            var ci = index.getClassByName(io.vidocq.vauban.indexer.model.DotName.of(fqn)).orElse(null);
            if (ci == null) continue;
            var pkg = packageOf(fqn);
            var bundle = byPackage.computeIfAbsent(pkg,
                    k -> new Bundle(new TreeSet<>(), new ArrayList<>(), new ArrayList<>()));

            // create(): a co-located provider may instantiate package-private (top-level) beans too.
            if (isInstantiableNoArg(ci)) bundle.noArg().add(fqn);

            // injectField(): non-private, non-static @Inject fields (package-private OK — same package).
            for (var f : ci.fields()) {
                if (f.isStatic()) continue;
                if (f.annotations().stream().noneMatch(a -> a.name().equals(injectName))) continue;
                if (f.isPrivate()) {
                    warnings.add("Field injection for private field " + fqn + "#" + f.name()
                            + " still needs `opens … to io.vidocq.vauban.core`"
                            + " (make it package-private to drop the opens)");
                    continue;
                }
                var erasure = fieldErasure(f.type());
                if (erasure == null) continue; // primitive — skip
                bundle.fields().add(new io.vidocq.vauban.core.provider.ComponentProviderClassGenerator
                        .FieldInject(fqn, f.name(), erasure));
            }

            // invoke(): methods the container invokes reflectively today (producers, observers,
            // disposers, lifecycle, initializers). package-private OK — same package.
            for (var m : ci.methods()) {
                if (m.isConstructor() || m.isStaticInitializer()) continue;
                if (m.isPrivate() || m.isAbstract()) continue;
                boolean hasMethodAnnotation = m.annotations().stream().anyMatch(a ->
                        a.name().equals(producesName)
                        || a.name().equals(postConstructName)
                        || a.name().equals(preDestroyName)
                        || a.name().equals(injectName));
                boolean hasParamAnnotation = m.parameters().stream()
                        .flatMap(p -> p.annotations().stream())
                        .anyMatch(a -> a.name().equals(observesName)
                                || a.name().equals(observesAsyncName)
                                || a.name().equals(disposesName));
                if (!hasMethodAnnotation && !hasParamAnnotation) continue;

                var paramErasures = new ArrayList<String>();
                boolean skipMethod = false;
                for (var p : m.parameters()) {
                    var erasure = fieldErasure(p.type());
                    if (erasure == null) {
                        warnings.add("Skipping method " + fqn + "#" + m.name()
                                + ": parameter type is a non-nameable/primitive — cannot emit invokevirtual");
                        skipMethod = true;
                        break;
                    }
                    if (erasure.contains("$")) {
                        warnings.add("Skipping method " + fqn + "#" + m.name()
                                + ": parameter type " + erasure + " is a nested class — cannot safely cast");
                        skipMethod = true;
                        break;
                    }
                    paramErasures.add(erasure);
                }
                if (skipMethod) continue;

                boolean isVoid = m.returnType() instanceof io.vidocq.vauban.indexer.model.TypeInfo.VoidType;
                if (!isVoid && m.returnType() instanceof io.vidocq.vauban.indexer.model.TypeInfo.PrimitiveType) {
                    warnings.add("Skipping method " + fqn + "#" + m.name()
                            + ": primitive return type — only reference returns are supported");
                    continue;
                }
                String returnErasure = isVoid ? null : fieldErasure(m.returnType());
                bundle.methods().add(new io.vidocq.vauban.core.provider.ComponentProviderClassGenerator
                        .MethodInvoke(fqn, m.name(), paramErasures, m.isStatic(), isVoid, returnErasure));
            }
        }

        if (byPackage.isEmpty()) return;

        var providerFqns = new ArrayList<String>();
        for (var entry : byPackage.entrySet()) {
            var pkg = entry.getKey();
            var bundle = entry.getValue();
            if (bundle.noArg().isEmpty() && bundle.fields().isEmpty() && bundle.methods().isEmpty()) continue;
            var providerFqn = pkg.isEmpty() ? "_VaubanComponents" : pkg + "._VaubanComponents";
            try {
                var gen = io.vidocq.vauban.core.provider.ComponentProviderClassGenerator.generate(
                        providerFqn, List.copyOf(bundle.noArg()),
                        List.copyOf(bundle.fields()), List.copyOf(bundle.methods()));
                writeClassFile(config.outputDir(), gen.className(), gen.bytecode());
                providerFqns.add(providerFqn);
            } catch (Exception e) {
                warnings.add("Failed to generate component provider for package " + pkg + ": " + e.getMessage());
            }
        }
        if (providerFqns.isEmpty()) return;
        try {
            var svc = config.outputDir().resolve(
                    "META-INF/services/io.vidocq.vauban.api.VaubanComponentProvider");
            Files.createDirectories(svc.getParent());
            Files.write(svc, providerFqns, StandardCharsets.UTF_8);
        } catch (Exception e) {
            warnings.add("Failed to write component provider service file: " + e.getMessage());
        }
    }

    /** Returns the package name for a fully-qualified class name, or {@code ""} for the default package. */
    private static String packageOf(String fqn) {
        return fqn.contains(".") ? fqn.substring(0, fqn.lastIndexOf('.')) : "";
    }

    /**
     * Returns the erased type name for a field type, suitable for use as a {@code putfield}
     * descriptor. Returns {@code null} for primitive types (which cannot be {@code @Inject}ed)
     * and for void / wildcard (not valid field types in practice).
     */
    private static String fieldErasure(io.vidocq.vauban.indexer.model.TypeInfo type) {
        return switch (type) {
            case io.vidocq.vauban.indexer.model.TypeInfo.ClassType ct -> ct.name().value();
            case io.vidocq.vauban.indexer.model.TypeInfo.ParameterizedType pt -> pt.rawType().value();
            case io.vidocq.vauban.indexer.model.TypeInfo.ArrayType at -> {
                var component = fieldErasure(at.componentType());
                yield component == null ? null : component + "[]";
            }
            case io.vidocq.vauban.indexer.model.TypeInfo.TypeVariable tv ->
                    tv.bounds().isEmpty() ? "java.lang.Object"
                            : fieldErasure(tv.bounds().getFirst());
            case io.vidocq.vauban.indexer.model.TypeInfo.WildcardType wt ->
                    wt.upperBound() != null ? fieldErasure(wt.upperBound()) : "java.lang.Object";
            case io.vidocq.vauban.indexer.model.TypeInfo.PrimitiveType ignored -> null;
            case io.vidocq.vauban.indexer.model.TypeInfo.VoidType ignored -> null;
        };
    }

    /**
     * Non-abstract (top-level) class with a no-arg constructor reachable from a co-located generated
     * provider: a public OR package-private class with a non-private no-arg (or implicit default)
     * constructor. Package-private members are fine because the generated {@code _VaubanComponents}
     * lives in the same package; only {@code private} and nested ({@code $}) classes fall back to
     * reflection (the latter filtered out earlier).
     */
    private static boolean isInstantiableNoArg(io.vidocq.vauban.indexer.model.ClassInfo ci) {
        if (ci.isAbstract()) return false;
        var ctors = ci.methods().stream()
                .filter(io.vidocq.vauban.indexer.model.MethodInfo::isConstructor)
                .toList();
        if (ctors.isEmpty()) return true; // implicit default constructor (same access as the class)
        return ctors.stream().anyMatch(c -> c.parameters().isEmpty() && !c.isPrivate());
    }

    private static void scanClassesDirectory(Path classesDir, IndexBuilder indexBuilder,
                                              List<String> warnings) throws IOException {
        Files.walkFileTree(classesDir, new SimpleFileVisitor<>() {
            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) {
                var fileName = file.getFileName().toString();
                if (fileName.endsWith(".class") && !fileName.equals("module-info.class")
                        && !isGeneratedClass(fileName)) {
                    try {
                        var bytes = Files.readAllBytes(file);
                        indexBuilder.add(ClassFileScanner.scan(bytes));
                    } catch (Exception | Error e) {
                        warnings.add("Failed to scan " + file.getFileName() + ": " + e.getMessage());
                    }
                }
                return FileVisitResult.CONTINUE;
            }
        });
    }

    /** Returns true if the filename matches a Vauban-generated class. */
    private static boolean isGeneratedClass(String fileName) {
        var baseName = fileName.substring(0, fileName.length() - ".class".length());
        for (var suffix : GENERATED_SUFFIXES) {
            if (baseName.endsWith(suffix)) return true;
        }
        return false;
    }

    /** Checks if a generated class file already exists on disk. */
    private static boolean classFileExists(Path outputDir, String className) {
        return Files.exists(outputDir.resolve(className.replace('.', '/') + ".class"));
    }

    /** Reads bean class names from an existing vauban-beans.list in a directory. */
    private static List<String> readBeansListFromDirectory(Path dir) {
        var beansListFile = dir.resolve(BEANS_LIST_PATH);
        if (!Files.isRegularFile(beansListFile)) return List.of();
        try {
            return parseBeansList(Files.readAllLines(beansListFile, StandardCharsets.UTF_8));
        } catch (IOException e) {
            return List.of();
        }
    }

    /** Reads bean class names from an existing vauban-beans.list inside a JAR. */
    private static List<String> readBeansListFromJar(Path jarPath) {
        try (var jar = new JarFile(jarPath.toFile())) {
            var entry = jar.getEntry(BEANS_LIST_PATH);
            if (entry == null) return List.of();
            try (var reader = new BufferedReader(
                    new InputStreamReader(jar.getInputStream(entry), StandardCharsets.UTF_8))) {
                return parseBeansList(reader.lines().toList());
            }
        } catch (IOException e) {
            return List.of();
        }
    }

    /** Parses a beans list file, filtering comments and blank lines. */
    private static List<String> parseBeansList(List<String> lines) {
        return lines.stream()
                .map(String::strip)
                .filter(line -> !line.isEmpty() && !line.startsWith("#"))
                .toList();
    }

    /**
     * Serializes the {@code @Enhancement} result (target class → added annotation FQNs) to
     * {@code META-INF/vauban-enhancements.properties}, mirroring what the APT emits. Mirrors
     * {@code VaubanProcessor.writeEnhancementsPatch}; only modified configs contribute. A write
     * failure is non-fatal (the runtime falls back to reflective replay).
     */
    private static void writeEnhancementsPatch(Path outputDir,
            Map<io.vidocq.vauban.indexer.model.DotName,
                    List<io.vidocq.vauban.core.extensions.VaubanClassConfig>> modifications,
            List<String> warnings) {
        var patch = new TreeMap<String, List<String>>();
        for (var entry : modifications.entrySet()) {
            var added = new LinkedHashSet<String>();
            for (var cfg : entry.getValue()) {
                if (!cfg.isModified()) continue;
                for (var ann : cfg.getAddedAnnotations()) {
                    added.add(ann.getName());
                }
            }
            if (!added.isEmpty()) {
                patch.put(entry.getKey().value(), List.copyOf(added));
            }
        }
        if (patch.isEmpty()) return;
        try {
            var patchFile = outputDir.resolve(
                    io.vidocq.vauban.core.extensions.EnhancementPatchSerializer.PATCH_PATH);
            Files.createDirectories(patchFile.getParent());
            try (var os = Files.newOutputStream(patchFile)) {
                io.vidocq.vauban.core.extensions.EnhancementPatchSerializer.write(patch, os);
            }
        } catch (IOException e) {
            warnings.add("Failed to write enhancement patch: " + e.getMessage());
        }
    }

    private static void writeBeansList(Path outputDir, List<String> beanClassNames) throws IOException {
        var beansListFile = outputDir.resolve(BEANS_LIST_PATH);
        Files.createDirectories(beansListFile.getParent());

        var lines = new ArrayList<String>();
        lines.add("# Vauban discovered beans — generated at build time");
        lines.addAll(beanClassNames);

        Files.write(beansListFile, lines, StandardCharsets.UTF_8);
    }

    private static void writeClassFile(Path outputDir, String className, byte[] bytecode) throws IOException {
        var classFilePath = outputDir.resolve(className.replace('.', '/') + ".class");
        Files.createDirectories(classFilePath.getParent());
        Files.write(classFilePath, bytecode);
    }

    private static List<Class<?>> discoverBceClasses(ClassLoader cl) {
        var bceClasses = new ArrayList<Class<?>>();
        try {
            java.util.ServiceLoader.load(
                    jakarta.enterprise.inject.build.compatible.spi.BuildCompatibleExtension.class, cl)
                    .forEach(ext -> bceClasses.add(ext.getClass()));
        } catch (Exception ignored) {}
        return bceClasses;
    }

    private static List<Class<?>> loadArchiveClasses(
            io.vidocq.vauban.indexer.VaubanIndex index, ClassLoader cl) {
        var classes = new ArrayList<Class<?>>();
        for (var classInfo : index.getKnownClasses()) {
            try {
                classes.add(Class.forName(classInfo.name().value(), false, cl));
            } catch (ClassNotFoundException | NoClassDefFoundError _) {
                // NoClassDefFoundError: a transitive dependency referenced by this type
                // is absent from the classpath (e.g. jakarta.activation from microprofile-config-api).
                // We ignore it silently; the class will simply not be loaded for the
                // rest of the pipeline (BCE / proxy / interceptor). See VAU-MVN-001.
               // warnings.add("Failed to load class {} from classpath, ignoring: {}", classInfo.name().value());
            }
        }
        return classes;
    }
}
