package io.vidocq.vauban.maven.generate;

import io.vidocq.vauban.core.bean.discovery.BeanDiscovery;
import io.vidocq.vauban.core.bean.model.BeanDescriptor;
import io.vidocq.vauban.core.bean.model.BeanDescriptor.BeanKind;
import io.vidocq.vauban.core.interceptor.InterceptorSubclassGenerator;
import io.vidocq.vauban.core.proxy.RuntimeClientProxyGenerator;
import io.vidocq.vauban.indexer.IndexBuilder;
import io.vidocq.vauban.indexer.scanner.ClassFileScanner;
import io.vidocq.vauban.indexer.scanner.JarScanner;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.*;
import java.util.jar.JarFile;

/**
 * Core build-time logic for CDI bean discovery and code generation.
 * <p>
 * Scans dependency JARs and project classes, runs CDI bean discovery,
 * pre-generates client proxies and interceptor subclasses, and writes
 * a {@code META-INF/vauban-beans.list} file for runtime discovery.
 * <p>
 * Avoids double processing: JARs or project classes that already contain
 * a {@code vauban-beans.list} (e.g. generated by APT) are not re-discovered.
 * Proxy classes already present on disk are not regenerated.
 * <p>
 * This class has no Maven dependency and is independently testable.
 */
public final class VaubanGenerator {

    /** Location of the bean list file within the classpath. */
    public static final String BEANS_LIST_PATH = "META-INF/vauban-beans.list";


    /** Suffixes of classes generated by Vauban — excluded from index scanning. */
    private static final List<String> GENERATED_SUFFIXES = List.of(
            "_ClientProxy", "_Factory", "$$Intercepted"
    );

    /**
     * Configuration for the generator.
     *
     * @param dependencyJars    JAR files to scan for CDI beans
     * @param projectClassesDir project's compiled classes directory (may be null)
     * @param outputDir         where to write generated files
     * @param classLoader       ClassLoader with all deps + project classes for proxy generation (may be null to skip generation)
     */
    public record Config(
            List<Path> dependencyJars,
            Path projectClassesDir,
            Path outputDir,
            ClassLoader classLoader
    ) {
        public Config {
            dependencyJars = List.copyOf(dependencyJars);
        }

        /** Config without ClassLoader — discovery only, no proxy generation. */
        public Config(List<Path> dependencyJars, Path projectClassesDir, Path outputDir) {
            this(dependencyJars, projectClassesDir, outputDir, null);
        }
    }

    private VaubanGenerator() {}

    /**
     * Scan dependencies and project classes, discover CDI beans,
     * generate proxies/interceptor subclasses, and write the bean list file.
     * <p>
     * Already-processed sources (containing {@code vauban-beans.list}) are not
     * re-discovered. Their bean names are collected and merged into the final list.
     * Proxy/interceptor classes already on disk are not regenerated.
     *
     * @param config generation configuration
     * @return result with discovered beans, generated classes, and warnings
     * @throws IOException if scanning or writing fails
     */
    public static GenerationResult generate(Config config) throws IOException {
        var indexBuilder = new IndexBuilder();
        var warnings = new ArrayList<String>();
        var alreadyKnownBeans = new LinkedHashSet<String>();

        // 1. Scan dependency JARs
        for (var dep : config.dependencyJars()) {
            if (Files.isDirectory(dep)) {
                // Reactor dependency — check for existing beans list
                var existingBeans = readBeansListFromDirectory(dep);
                if (!existingBeans.isEmpty()) {
                    alreadyKnownBeans.addAll(existingBeans);
                } else {
                    scanClassesDirectory(dep, indexBuilder, warnings);
                }
            } else if (Files.isRegularFile(dep)) {
                // JAR dependency — check for existing beans list
                var existingBeans = readBeansListFromJar(dep);
                if (!existingBeans.isEmpty()) {
                    alreadyKnownBeans.addAll(existingBeans);
                } else {
                    try {
                        var classInfos = JarScanner.scan(dep);
                        indexBuilder.addAll(classInfos);
                    } catch (IOException e) {
                        warnings.add("Failed to scan JAR " + dep.getFileName() + ": " + e.getMessage());
                    }
                }
            } else {
                warnings.add("Skipping non-existent dependency: " + dep);
            }
        }

        // 2. Scan project classes directory (skip if APT already processed it)
        boolean projectAlreadyProcessed = false;
        if (config.projectClassesDir() != null && Files.isDirectory(config.projectClassesDir())) {
            var existingBeans = readBeansListFromDirectory(config.projectClassesDir());
            if (!existingBeans.isEmpty()) {
                alreadyKnownBeans.addAll(existingBeans);
                projectAlreadyProcessed = true;
                // Still scan project classes for index — needed for interceptor generation
                scanClassesDirectory(config.projectClassesDir(), indexBuilder, warnings);
            } else {
                scanClassesDirectory(config.projectClassesDir(), indexBuilder, warnings);
            }
        }

        // 3. Build merged index
        var index = indexBuilder.build();
        if (index.size() == 0 && alreadyKnownBeans.isEmpty()) {
            return new GenerationResult(List.of(), List.of(), List.of(), warnings);
        }

        // 3b. Run BCE @Enhancement for non-pre-processed classes (if ClassLoader available)
        if (config.classLoader() != null) {
            var bceClasses = discoverBceClasses(config.classLoader());
            if (!bceClasses.isEmpty()) {
                var archiveClasses = loadArchiveClasses(index, config.classLoader());
                var enhMods = io.vidocq.vauban.core.extensions.BceProcessor.processEnhancementOnly(
                        bceClasses, archiveClasses, index, config.classLoader());

                if (!enhMods.isEmpty()) {
                    // Rebuild index with synthetic scope annotations from Enhancement
                    var enrichedBuilder = new IndexBuilder();
                    for (var classInfo : index.getKnownClasses()) {
                        var mods = enhMods.get(classInfo.name());
                        if (mods != null) {
                            var newAnnotations = new java.util.ArrayList<>(classInfo.annotations());
                            for (var mod : mods) {
                                for (var ann : mod.getAddedAnnotations()) {
                                    newAnnotations.add(new io.vidocq.vauban.indexer.model.AnnotationInfo(
                                            io.vidocq.vauban.indexer.model.DotName.of(ann.getName()),
                                            java.util.Map.of()));
                                }
                            }
                            enrichedBuilder.add(new io.vidocq.vauban.indexer.model.ClassInfo(
                                    classInfo.name(), classInfo.superName(), classInfo.interfaces(),
                                    classInfo.accessFlags(), classInfo.fields(), classInfo.methods(),
                                    newAnnotations, classInfo.kind()));
                        } else {
                            enrichedBuilder.add(classInfo);
                        }
                    }
                    index = enrichedBuilder.build();
                }
            }
        }

        // 5. Run CDI bean discovery on enriched index
        var discovery = new BeanDiscovery(index);
        var beans = discovery.discoverBeans();

        // 6. Partition: already-known vs newly-discovered
        var newBeans = new ArrayList<BeanDescriptor>();
        var allBeanClassNames = new LinkedHashSet<>(alreadyKnownBeans);

        for (var bean : beans) {
            var className = bean.beanClass().value();
            allBeanClassNames.add(className);
            if (!alreadyKnownBeans.contains(className)) {
                newBeans.add(bean);
            }
        }

        var sortedBeanClassNames = allBeanClassNames.stream().sorted().toList();

        // 7. Write merged META-INF/vauban-beans.list (only if we have new beans to add)
        if (!newBeans.isEmpty() || !projectAlreadyProcessed) {
            writeBeansList(config.outputDir(), sortedBeanClassNames);
        }

        // 8. Pre-generate proxies and interceptor subclasses (if ClassLoader provided)
        //    Skip classes whose proxy/interceptor already exists on disk
        var generatedProxies = new ArrayList<String>();
        var generatedInterceptors = new ArrayList<String>();

        if (config.classLoader() != null) {
            // For newly discovered beans: generate everything
            // For already-known beans in project: generate interceptors only (APT can't)
            var beansToProcess = projectAlreadyProcessed
                    ? beans  // all beans including project ones (for interceptors)
                    : newBeans;

            for (var bean : beansToProcess) {
                var className = bean.beanClass().value();
                Class<?> clazz;
                try {
                    clazz = Class.forName(className, false, config.classLoader());
                } catch (ClassNotFoundException | NoClassDefFoundError _) {
                    // NoClassDefFoundError: une dépendance transitive référencée par cette classe
                    // est absente du classpath fourni au plugin (cf. VAU-MVN-001).
                    warnings.add("Cannot load class for generation: " + className);
                    continue;
                }

                // Client proxy for normal-scoped beans (skip if already exists)
                if (bean.scope().isNormal() && !alreadyKnownBeans.contains(className)) {
                    var proxyClassName = className + "_ClientProxy";
                    if (!classFileExists(config.outputDir(), proxyClassName)) {
                        try {
                            var generated = RuntimeClientProxyGenerator.generate(clazz);
                            writeClassFile(config.outputDir(), generated.className(), generated.bytecode());
                            generatedProxies.add(generated.className());
                        } catch (Exception e) {
                            warnings.add("Failed to generate proxy for " + className + ": " + e.getMessage());
                        }
                    }
                }

                // Interceptor subclass for managed beans with interceptor bindings
                // Always generate if not already on disk (APT does not generate these)
                if (bean.kind() == BeanKind.MANAGED
                        && !bean.interceptorBindings().isEmpty()
                        && !java.lang.reflect.Modifier.isFinal(clazz.getModifiers())) {
                    var interceptorClassName = className + "$$Intercepted";
                    if (!classFileExists(config.outputDir(), interceptorClassName)) {
                        try {
                            var generated = InterceptorSubclassGenerator.generate(clazz);
                            writeClassFile(config.outputDir(), generated.className(), generated.bytecode());
                            generatedInterceptors.add(generated.className());
                        } catch (Exception e) {
                            warnings.add("Failed to generate interceptor subclass for " + className + ": " + e.getMessage());
                        }
                    }
                }
            }
        }

        return new GenerationResult(sortedBeanClassNames, generatedProxies, generatedInterceptors, warnings);
    }

    private static void scanClassesDirectory(Path classesDir, IndexBuilder indexBuilder,
                                              List<String> warnings) throws IOException {
        Files.walkFileTree(classesDir, new SimpleFileVisitor<>() {
            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) {
                var fileName = file.getFileName().toString();
                if (fileName.endsWith(".class") && !fileName.equals("module-info.class")
                        && !isGeneratedClass(fileName)) {
                    try {
                        var bytes = Files.readAllBytes(file);
                        indexBuilder.add(ClassFileScanner.scan(bytes));
                    } catch (Exception | Error e) {
                        warnings.add("Failed to scan " + file.getFileName() + ": " + e.getMessage());
                    }
                }
                return FileVisitResult.CONTINUE;
            }
        });
    }

    /** Returns true if the filename matches a Vauban-generated class. */
    private static boolean isGeneratedClass(String fileName) {
        var baseName = fileName.substring(0, fileName.length() - ".class".length());
        for (var suffix : GENERATED_SUFFIXES) {
            if (baseName.endsWith(suffix)) return true;
        }
        return false;
    }

    /** Checks if a generated class file already exists on disk. */
    private static boolean classFileExists(Path outputDir, String className) {
        return Files.exists(outputDir.resolve(className.replace('.', '/') + ".class"));
    }

    /** Reads bean class names from an existing vauban-beans.list in a directory. */
    private static List<String> readBeansListFromDirectory(Path dir) {
        var beansListFile = dir.resolve(BEANS_LIST_PATH);
        if (!Files.isRegularFile(beansListFile)) return List.of();
        try {
            return parseBeansList(Files.readAllLines(beansListFile, StandardCharsets.UTF_8));
        } catch (IOException e) {
            return List.of();
        }
    }

    /** Reads bean class names from an existing vauban-beans.list inside a JAR. */
    private static List<String> readBeansListFromJar(Path jarPath) {
        try (var jar = new JarFile(jarPath.toFile())) {
            var entry = jar.getEntry(BEANS_LIST_PATH);
            if (entry == null) return List.of();
            try (var reader = new BufferedReader(
                    new InputStreamReader(jar.getInputStream(entry), StandardCharsets.UTF_8))) {
                return parseBeansList(reader.lines().toList());
            }
        } catch (IOException e) {
            return List.of();
        }
    }

    /** Parses a beans list file, filtering comments and blank lines. */
    private static List<String> parseBeansList(List<String> lines) {
        return lines.stream()
                .map(String::strip)
                .filter(line -> !line.isEmpty() && !line.startsWith("#"))
                .toList();
    }

    private static void writeBeansList(Path outputDir, List<String> beanClassNames) throws IOException {
        var beansListFile = outputDir.resolve(BEANS_LIST_PATH);
        Files.createDirectories(beansListFile.getParent());

        var lines = new ArrayList<String>();
        lines.add("# Vauban discovered beans — generated at build time");
        lines.addAll(beanClassNames);

        Files.write(beansListFile, lines, StandardCharsets.UTF_8);
    }

    private static void writeClassFile(Path outputDir, String className, byte[] bytecode) throws IOException {
        var classFilePath = outputDir.resolve(className.replace('.', '/') + ".class");
        Files.createDirectories(classFilePath.getParent());
        Files.write(classFilePath, bytecode);
    }

    private static List<Class<?>> discoverBceClasses(ClassLoader cl) {
        var bceClasses = new ArrayList<Class<?>>();
        try {
            java.util.ServiceLoader.load(
                    jakarta.enterprise.inject.build.compatible.spi.BuildCompatibleExtension.class, cl)
                    .forEach(ext -> bceClasses.add(ext.getClass()));
        } catch (Exception ignored) {}
        return bceClasses;
    }

    private static List<Class<?>> loadArchiveClasses(
            io.vidocq.vauban.indexer.VaubanIndex index, ClassLoader cl) {
        var classes = new ArrayList<Class<?>>();
        for (var classInfo : index.getKnownClasses()) {
            try {
                classes.add(Class.forName(classInfo.name().value(), false, cl));
            } catch (ClassNotFoundException | NoClassDefFoundError _) {
                // NoClassDefFoundError: une dépendance transitive référencée par ce type
                // est absente du classpath (ex: jakarta.activation depuis microprofile-config-api).
                // On ignore silencieusement, la classe ne sera simplement pas chargée pour la
                // suite du pipeline (BCE / proxy / interceptor). Cf. VAU-MVN-001.
            }
        }
        return classes;
    }
}
