/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.vauban.maven.generate;

import io.vidocq.vauban.core.bean.discovery.BeanDiscovery;
import io.vidocq.vauban.core.bean.model.BeanDescriptor;
import io.vidocq.vauban.core.bean.model.BeanDescriptor.BeanKind;
import io.vidocq.vauban.core.interceptor.InterceptorSubclassGenerator;
import io.vidocq.vauban.core.proxy.RuntimeClientProxyGenerator;
import io.vidocq.vauban.indexer.IndexBuilder;
import io.vidocq.vauban.indexer.codegen.ComponentCollector;
import io.vidocq.vauban.indexer.codegen.ProvidedClass;
import io.vidocq.vauban.indexer.scanner.ClassFileScanner;
import io.vidocq.vauban.indexer.scanner.JarScanner;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.*;
import java.util.jar.JarFile;

/**
 * Core build-time logic for CDI bean discovery and code generation.
 * <p>
 * Scans dependency JARs and project classes, runs CDI bean discovery,
 * pre-generates client proxies and interceptor subclasses, and writes
 * a {@code META-INF/vauban-beans.list} file for runtime discovery.
 * <p>
 * Avoids double processing: JARs or project classes that already contain
 * a {@code vauban-beans.list} (e.g. generated by APT) are not re-discovered.
 * Proxy classes already present on disk are not regenerated.
 * <p>
 * This class has no Maven dependency and is independently testable.
 */
public final class VaubanGenerator {

    /** Location of the bean list file within the classpath. */
    public static final String BEANS_LIST_PATH = "META-INF/vauban-beans.list";


    /** Suffixes of classes generated by Vauban — excluded from index scanning. */
    private static final List<String> GENERATED_SUFFIXES = List.of(
            "_ClientProxy", "_Factory", "$$Intercepted"
    );

    /**
     * Configuration for the generator.
     *
     * @param dependencyJars    JAR files to scan for CDI beans
     * @param projectClassesDir project's compiled classes directory (may be null)
     * @param outputDir         where to write generated files
     * @param classLoader       ClassLoader with all deps + project classes for proxy generation (may be null to skip generation)
     */
    public record Config(
            List<Path> dependencyJars,
            Path projectClassesDir,
            Path outputDir,
            ClassLoader classLoader
    ) {
        public Config {
            dependencyJars = List.copyOf(dependencyJars);
        }

        /** Config without ClassLoader — discovery only, no proxy generation. */
        public Config(List<Path> dependencyJars, Path projectClassesDir, Path outputDir) {
            this(dependencyJars, projectClassesDir, outputDir, null);
        }
    }

    private VaubanGenerator() {}

    /**
     * Scan dependencies and project classes, discover CDI beans,
     * generate proxies/interceptor subclasses, and write the bean list file.
     * <p>
     * Already-processed sources (containing {@code vauban-beans.list}) are not
     * re-discovered. Their bean names are collected and merged into the final list.
     * Proxy/interceptor classes already on disk are not regenerated.
     *
     * @param config generation configuration
     * @return result with discovered beans, generated classes, and warnings
     * @throws IOException if scanning or writing fails
     */
    public static GenerationResult generate(Config config) throws IOException {
        var indexBuilder = new IndexBuilder();
        var warnings = new ArrayList<String>();
        var alreadyKnownBeans = new LinkedHashSet<String>();

        // 1. Scan dependency JARs
        for (var dep : config.dependencyJars()) {
            if (Files.isDirectory(dep)) {
                // Reactor dependency — check for existing beans list
                var existingBeans = readBeansListFromDirectory(dep);
                if (!existingBeans.isEmpty()) {
                    alreadyKnownBeans.addAll(existingBeans);
                } else {
                    scanClassesDirectory(dep, indexBuilder, warnings);
                }
            } else if (Files.isRegularFile(dep)) {
                // JAR dependency — check for existing beans list
                var existingBeans = readBeansListFromJar(dep);
                if (!existingBeans.isEmpty()) {
                    alreadyKnownBeans.addAll(existingBeans);
                } else {
                    try {
                        var classInfos = JarScanner.scan(dep);
                        indexBuilder.addAll(classInfos);
                    } catch (IOException e) {
                        warnings.add("Failed to scan JAR " + dep.getFileName() + ": " + e.getMessage());
                    }
                }
            } else {
                warnings.add("Skipping non-existent dependency: " + dep);
            }
        }

        // 2. Scan project classes directory (skip if APT already processed it)
        boolean projectAlreadyProcessed = false;
        if (config.projectClassesDir() != null && Files.isDirectory(config.projectClassesDir())) {
            var existingBeans = readBeansListFromDirectory(config.projectClassesDir());
            if (!existingBeans.isEmpty()) {
                alreadyKnownBeans.addAll(existingBeans);
                projectAlreadyProcessed = true;
                // Still scan project classes for index — needed for interceptor generation
                scanClassesDirectory(config.projectClassesDir(), indexBuilder, warnings);
            } else {
                scanClassesDirectory(config.projectClassesDir(), indexBuilder, warnings);
            }
        }

        // 3. Build merged index
        var index = indexBuilder.build();
        if (index.size() == 0 && alreadyKnownBeans.isEmpty()) {
            return new GenerationResult(List.of(), List.of(), List.of(), List.of(), warnings);
        }

        // 3b. Run BCE @Enhancement for non-pre-processed classes (if ClassLoader available)
        if (config.classLoader() != null) {
            var bceClasses = discoverBceClasses(config.classLoader());
            if (!bceClasses.isEmpty()) {
                var archiveClasses = loadArchiveClasses(index, config.classLoader());
                var enhMods = io.vidocq.vauban.core.extensions.BceProcessor.processEnhancementOnly(
                        bceClasses, archiveClasses, index, config.classLoader());

                // Brique A for plugin-processed modules (cervantes/cyrano/knock/dirac, which use
                // this plugin instead of the APT): freeze the @Enhancement result as a static
                // patch so the runtime applies it without re-instantiating/replaying the BCE
                // reflectively — removing one reason for `opens … to io.vidocq.vauban.core`.
                writeEnhancementsPatch(config.outputDir(), enhMods, warnings);

                if (!enhMods.isEmpty()) {
                    // Rebuild index with synthetic scope annotations from Enhancement
                    var enrichedBuilder = new IndexBuilder();
                    for (var classInfo : index.getKnownClasses()) {
                        var mods = enhMods.get(classInfo.name());
                        if (mods != null) {
                            var newAnnotations = new java.util.ArrayList<>(classInfo.annotations());
                            for (var mod : mods) {
                                for (var ann : mod.getAddedAnnotations()) {
                                    newAnnotations.add(new io.vidocq.vauban.indexer.model.AnnotationInfo(
                                            io.vidocq.vauban.indexer.model.DotName.of(ann.getName()),
                                            java.util.Map.of()));
                                }
                            }
                            enrichedBuilder.add(new io.vidocq.vauban.indexer.model.ClassInfo(
                                    classInfo.name(), classInfo.superName(), classInfo.interfaces(),
                                    classInfo.accessFlags(), classInfo.fields(), classInfo.methods(),
                                    newAnnotations, classInfo.kind()));
                        } else {
                            enrichedBuilder.add(classInfo);
                        }
                    }
                    index = enrichedBuilder.build();
                }
            }
        }

        // 5. Run CDI bean discovery on enriched index
        var discovery = new BeanDiscovery(index);
        var beans = discovery.discoverBeans();

        // 6. Partition: already-known vs newly-discovered
        var newBeans = new ArrayList<BeanDescriptor>();
        var allBeanClassNames = new LinkedHashSet<>(alreadyKnownBeans);

        for (var bean : beans) {
            var className = bean.beanClass().value();
            allBeanClassNames.add(className);
            if (!alreadyKnownBeans.contains(className)) {
                newBeans.add(bean);
            }
        }

        var sortedBeanClassNames = allBeanClassNames.stream().sorted().toList();

        // 7. Write merged META-INF/vauban-beans.list (only if we have new beans to add)
        if (!newBeans.isEmpty() || !projectAlreadyProcessed) {
            writeBeansList(config.outputDir(), sortedBeanClassNames);
        }

        // 7b. Weave the synthetic (ProxyLink) client-proxy entry constructor into this
        //     module's normal-scoped beans (Vidocq/vauban#24 phase 2) — the app's source
        //     never declares it. Runs BEFORE proxy generation so classes loaded below
        //     already carry the marker and the generators chain to it.
        var wovenBeans = config.projectClassesDir() == null
                ? List.<String>of()
                : ProxyLinkWeaving.weave(config.projectClassesDir(), index, config.classLoader(),
                        beans, warnings);

        // 8. Pre-generate proxies and interceptor subclasses (if ClassLoader provided)
        //    Skip classes whose proxy/interceptor already exists on disk
        var generatedProxies = new ArrayList<String>();
        var generatedInterceptors = new ArrayList<String>();

        if (config.classLoader() != null) {
            // For newly discovered beans: generate everything
            // For already-known beans in project: generate interceptors only (APT can't)
            var beansToProcess = projectAlreadyProcessed
                    ? beans  // all beans including project ones (for interceptors)
                    : newBeans;

            for (var bean : beansToProcess) {
                var className = bean.beanClass().value();
                Class<?> clazz;
                try {
                    clazz = Class.forName(className, false, config.classLoader());
                } catch (ClassNotFoundException | NoClassDefFoundError _) {
                    // NoClassDefFoundError: a transitive dependency referenced by this class
                    // is absent from the classpath provided to the plugin (see VAU-MVN-001).
                   warnings.add("Cannot load class for generation: " + className);
                    continue;
                }

                // Client proxy for normal-scoped beans (skip if already exists)
                if (bean.scope().isNormal() && !alreadyKnownBeans.contains(className)) {
                    var proxyClassName = className + "_ClientProxy";
                    if (!classFileExists(config.outputDir(), proxyClassName)) {
                        try {
                            var generated = RuntimeClientProxyGenerator.generate(clazz);
                            writeClassFile(config.outputDir(), generated.className(), generated.bytecode());
                            generatedProxies.add(generated.className());
                        } catch (Exception e) {
                            warnings.add("Failed to generate proxy for " + className + ": " + e.getMessage());
                        }
                    }
                }

                // Interceptor subclass for managed beans with interceptor bindings
                // Always generate if not already on disk (APT does not generate these)
                if (bean.kind() == BeanKind.MANAGED
                        && !bean.interceptorBindings().isEmpty()
                        && !java.lang.reflect.Modifier.isFinal(clazz.getModifiers())) {
                    var interceptorClassName = className + "$$Intercepted";
                    if (!classFileExists(config.outputDir(), interceptorClassName)) {
                        try {
                            var generated = InterceptorSubclassGenerator.generate(clazz);
                            writeClassFile(config.outputDir(), generated.className(), generated.bytecode());
                            generatedInterceptors.add(generated.className());
                        } catch (Exception e) {
                            warnings.add("Failed to generate interceptor subclass for " + className + ": " + e.getMessage());
                        }
                    }
                }
            }
        }

        // 8b. Point the proxies of woven beans at the marker — APT-emitted proxies predate it
        //     and still chain a business constructor; freshly generated ones already target it
        //     (the rewrite is idempotent).
        if (config.projectClassesDir() != null && !wovenBeans.isEmpty()) {
            ProxyLinkWeaving.retargetProxies(config.projectClassesDir(), wovenBeans, warnings);
        }

        // 9. Generate the per-module _VaubanComponents provider (bytecode — no javac in the plugin)
        //    for THIS module's public no-arg beans, so the container instantiates them in-module
        //    without reflection and the module can drop `opens … to io.vidocq.vauban.core`.
        generateComponentProvider(config, index, beans, warnings);

        return new GenerationResult(sortedBeanClassNames, generatedProxies, generatedInterceptors,
                wovenBeans, warnings);
    }

    /**
     * Emits one {@code <pkg>/_VaubanComponents.class} <em>per package</em> that has managed beans
     * compiled into this module ({@code projectClassesDir}), plus a class-path service file listing
     * them all. A per-package provider is co-located with its beans, so it can {@code new}/inject/
     * invoke even their <strong>package-private</strong> members without reflection — which a single
     * common-package provider could not reach across packages. Beans from dependency jars are
     * excluded — they carry their own provider. The module still needs a hand-written
     * {@code provides io.vidocq.vauban.api.VaubanComponentProvider with pkgA._VaubanComponents,
     * pkgB._VaubanComponents;} (all providers) for the module path; the class-path service file
     * covers the unnamed-module case.
     */
    /**
     * The produced concrete class of a producer bean, loaded via {@code cl}, or {@code null} when
     * the produced type is an interface (reflect.Proxy at runtime) or cannot be loaded. Mirrors the
     * runtime {@code InterceptorBeanWrapper.resolveProxyTargetClass}: first concrete bean type.
     */
    private static Class<?> resolveProducedClass(BeanDescriptor bean, ClassLoader cl) {
        for (var t : bean.types()) {
            if (!(t instanceof io.vidocq.vauban.indexer.model.TypeInfo.ClassType ct)) {
                continue;
            }
            var fqn = ct.name().value();
            if ("java.lang.Object".equals(fqn)) {
                continue;
            }
            try {
                var c = Class.forName(fqn, false, cl);
                if (!c.isInterface()) {
                    return c;
                }
            } catch (ClassNotFoundException | NoClassDefFoundError ignore) {
                // produced type not on the plugin's classpath — leave it to the runtime
            }
        }
        return null;
    }

    private static void generateComponentProvider(Config config,
            io.vidocq.vauban.indexer.VaubanIndex index,
            List<BeanDescriptor> beans, List<String> warnings) {
        var projectDir = config.projectClassesDir();
        if (projectDir == null) return;

        // Build the list of eligible managed classes: non-nested, in this module's classes dir.
        var provided = new ArrayList<ProvidedClass>();
        // Normal-scoped beans of this module get a <Bean>_ClientProxy (generated above via
        // RuntimeClientProxyGenerator); record them so the per-package provider can instantiate the
        // proxy in-module (createClientProxy → new <Bean>_ClientProxy()), no opens/exports needed.
        var clientProxyFqns = new java.util.LinkedHashSet<String>();
        for (var bean : beans) {
            if (bean.kind() != BeanKind.MANAGED) continue;
            var fqn = bean.beanClass().value();
            if (fqn.contains("$")) continue;               // nested → reflective fallback
            if (!classFileExists(projectDir, fqn)) continue; // not part of this module
            var ci = index.getClassByName(io.vidocq.vauban.indexer.model.DotName.of(fqn)).orElse(null);
            if (ci == null) continue;
            // instantiable=true: let ComponentCollector determine the constructor strategy
            provided.add(new ProvidedClass(fqn, ci, true));
            if (bean.scope().isNormal()) {
                clientProxyFqns.add(fqn + "_ClientProxy");
            }
        }

        // Build-time proxies for normal-scoped producers of fully-public external classes (issue
        // #42, Stage 1.6 — bytecode parity with the APT source path). The proxy is written into the
        // producer's own package (this module) and registered under the produced-type key the
        // runtime looks up before its reflective fallback → zero opens on the module path.
        var producerProxiesByPackage =
                new java.util.LinkedHashMap<String,
                        java.util.List<io.vidocq.vauban.core.provider.ComponentProviderClassGenerator.ProducerProxy>>();
        if (config.classLoader() != null) {
            for (var bean : beans) {
                if (bean.kind() != BeanKind.PRODUCER_METHOD && bean.kind() != BeanKind.PRODUCER_FIELD) {
                    continue;
                }
                if (!bean.scope().isNormal()) {
                    continue;
                }
                var holderFqn = bean.beanClass().value();
                if (!classFileExists(projectDir, holderFqn)) {
                    continue; // the producer holder is not part of this module
                }
                var producedClass = resolveProducedClass(bean, config.classLoader());
                if (producedClass == null) {
                    continue; // interface-typed (reflect.Proxy at runtime) or unresolvable
                }
                var verdict = io.vidocq.vauban.core.proxy.ProducerProxyEligibility.of(producedClass);
                if (!verdict.eligible()) {
                    warnings.add("Producer of " + producedClass.getName()
                            + " is not build-time proxyable (" + verdict
                            + "); the runtime will generate its proxy (needs `opens "
                            + packageOf(producedClass.getName()) + " to io.vidocq.vauban.core;`).");
                    continue;
                }
                var producerPkg = packageOf(holderFqn);
                var producedFqn = producedClass.getName();
                var producedSimple = producedFqn.substring(producedFqn.lastIndexOf('.') + 1)
                        .replace('$', '_');
                var proxyFqn = (producerPkg.isEmpty() ? "" : producerPkg + ".")
                        + producedSimple + "$$"
                        + Integer.toHexString(producedFqn.hashCode()) + "_ClientProxy";
                if (!classFileExists(config.outputDir(), proxyFqn)) {
                    try {
                        var gen = RuntimeClientProxyGenerator.generateProducerProxyAt(
                                producedClass, proxyFqn);
                        writeClassFile(config.outputDir(), gen.className(), gen.bytecode());
                    } catch (Exception e) {
                        warnings.add("Failed to generate producer proxy for " + producedFqn
                                + ": " + e.getMessage());
                        continue;
                    }
                }
                producerProxiesByPackage
                        .computeIfAbsent(producerPkg, k -> new ArrayList<>())
                        .add(new io.vidocq.vauban.core.provider.ComponentProviderClassGenerator
                                .ProducerProxy(producedFqn + "_ClientProxy", proxyFqn));
            }
        }

        var packages = ComponentCollector.collect(provided, warnings);
        if (packages.isEmpty() && producerProxiesByPackage.isEmpty()) return;

        var providerFqns = new ArrayList<String>();
        var emittedProviderPackages = new java.util.HashSet<String>();
        for (var pkg : packages) {
            var providerFqn = pkg.providerFqn();
            try {
                // Proxies of this package's beans (FQN package equals the provider's package).
                var pkgProxies = clientProxyFqns.stream()
                        .filter(p -> packageOf(p).equals(pkg.packageName()))
                        .toList();
                var pkgProducerProxies =
                        producerProxiesByPackage.getOrDefault(pkg.packageName(), List.of());
                // Bytecode generator handles both no-arg and injected-constructor components.
                var gen = io.vidocq.vauban.core.provider.ComponentProviderClassGenerator.generate(
                        providerFqn, pkg.components(), pkg.fields(), pkg.methods(),
                        pkgProxies, pkgProducerProxies);
                writeClassFile(config.outputDir(), gen.className(), gen.bytecode());
                providerFqns.add(providerFqn);
                emittedProviderPackages.add(pkg.packageName());
            } catch (Exception e) {
                warnings.add("Failed to generate component provider for package "
                        + pkg.packageName() + ": " + e.getMessage());
            }
        }
        // A producer whose holder package has no other in-module component still needs a provider
        // for its produced-type proxy (issue #42). The module-info `provides` for such a package is
        // the user's responsibility (as for any bean package).
        for (var entry : producerProxiesByPackage.entrySet()) {
            if (emittedProviderPackages.contains(entry.getKey())) continue;
            var providerFqn = entry.getKey().isEmpty()
                    ? "_VaubanComponents" : entry.getKey() + "._VaubanComponents";
            try {
                var gen = io.vidocq.vauban.core.provider.ComponentProviderClassGenerator.generate(
                        providerFqn, List.of(), List.of(), List.of(), List.of(), entry.getValue());
                writeClassFile(config.outputDir(), gen.className(), gen.bytecode());
                providerFqns.add(providerFqn);
            } catch (Exception e) {
                warnings.add("Failed to generate producer-only component provider for package "
                        + entry.getKey() + ": " + e.getMessage());
            }
        }
        if (providerFqns.isEmpty()) return;
        try {
            var svc = config.outputDir().resolve(
                    "META-INF/services/io.vidocq.vauban.api.VaubanComponentProvider");
            Files.createDirectories(svc.getParent());
            Files.write(svc, providerFqns, StandardCharsets.UTF_8);
        } catch (Exception e) {
            warnings.add("Failed to write component provider service file: " + e.getMessage());
        }
    }

    private static void scanClassesDirectory(Path classesDir, IndexBuilder indexBuilder,
                                              List<String> warnings) throws IOException {
        Files.walkFileTree(classesDir, new SimpleFileVisitor<>() {
            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) {
                var fileName = file.getFileName().toString();
                if (fileName.endsWith(".class") && !fileName.equals("module-info.class")
                        && !isGeneratedClass(fileName)) {
                    try {
                        var bytes = Files.readAllBytes(file);
                        indexBuilder.add(ClassFileScanner.scan(bytes));
                    } catch (Exception | Error e) {
                        warnings.add("Failed to scan " + file.getFileName() + ": " + e.getMessage());
                    }
                }
                return FileVisitResult.CONTINUE;
            }
        });
    }

    /** Returns true if the filename matches a Vauban-generated class. */
    private static boolean isGeneratedClass(String fileName) {
        var baseName = fileName.substring(0, fileName.length() - ".class".length());
        for (var suffix : GENERATED_SUFFIXES) {
            if (baseName.endsWith(suffix)) return true;
        }
        return false;
    }

    /** Checks if a generated class file already exists on disk. */
    private static boolean classFileExists(Path outputDir, String className) {
        return Files.exists(outputDir.resolve(className.replace('.', '/') + ".class"));
    }

    /** Reads bean class names from an existing vauban-beans.list in a directory. */
    private static List<String> readBeansListFromDirectory(Path dir) {
        var beansListFile = dir.resolve(BEANS_LIST_PATH);
        if (!Files.isRegularFile(beansListFile)) return List.of();
        try {
            return parseBeansList(Files.readAllLines(beansListFile, StandardCharsets.UTF_8));
        } catch (IOException e) {
            return List.of();
        }
    }

    /** Reads bean class names from an existing vauban-beans.list inside a JAR. */
    private static List<String> readBeansListFromJar(Path jarPath) {
        try (var jar = new JarFile(jarPath.toFile())) {
            var entry = jar.getEntry(BEANS_LIST_PATH);
            if (entry == null) return List.of();
            try (var reader = new BufferedReader(
                    new InputStreamReader(jar.getInputStream(entry), StandardCharsets.UTF_8))) {
                return parseBeansList(reader.lines().toList());
            }
        } catch (IOException e) {
            return List.of();
        }
    }

    /** Parses a beans list file, filtering comments and blank lines. */
    private static List<String> parseBeansList(List<String> lines) {
        return lines.stream()
                .map(String::strip)
                .filter(line -> !line.isEmpty() && !line.startsWith("#"))
                .toList();
    }

    /**
     * Serializes the {@code @Enhancement} result (target class → added annotation FQNs) to
     * {@code META-INF/vauban-enhancements.properties}, mirroring what the APT emits. Mirrors
     * {@code VaubanProcessor.writeEnhancementsPatch}; only modified configs contribute. A write
     * failure is non-fatal (the runtime falls back to reflective replay).
     */
    private static void writeEnhancementsPatch(Path outputDir,
            Map<io.vidocq.vauban.indexer.model.DotName,
                    List<io.vidocq.vauban.core.extensions.VaubanClassConfig>> modifications,
            List<String> warnings) {
        var patch = new TreeMap<String, List<String>>();
        for (var entry : modifications.entrySet()) {
            var added = new LinkedHashSet<String>();
            for (var cfg : entry.getValue()) {
                if (!cfg.isModified()) continue;
                for (var ann : cfg.getAddedAnnotations()) {
                    added.add(ann.getName());
                }
            }
            if (!added.isEmpty()) {
                patch.put(entry.getKey().value(), List.copyOf(added));
            }
        }
        if (patch.isEmpty()) return;
        try {
            var patchFile = outputDir.resolve(
                    io.vidocq.vauban.core.extensions.EnhancementPatchSerializer.PATCH_PATH);
            Files.createDirectories(patchFile.getParent());
            try (var os = Files.newOutputStream(patchFile)) {
                io.vidocq.vauban.core.extensions.EnhancementPatchSerializer.write(patch, os);
            }
        } catch (IOException e) {
            warnings.add("Failed to write enhancement patch: " + e.getMessage());
        }
    }

    private static void writeBeansList(Path outputDir, List<String> beanClassNames) throws IOException {
        var beansListFile = outputDir.resolve(BEANS_LIST_PATH);
        Files.createDirectories(beansListFile.getParent());

        var lines = new ArrayList<String>();
        lines.add("# Vauban discovered beans — generated at build time");
        lines.addAll(beanClassNames);

        Files.write(beansListFile, lines, StandardCharsets.UTF_8);
    }

    private static void writeClassFile(Path outputDir, String className, byte[] bytecode) throws IOException {
        var classFilePath = outputDir.resolve(className.replace('.', '/') + ".class");
        Files.createDirectories(classFilePath.getParent());
        Files.write(classFilePath, bytecode);
    }

    /** Package of a top-level FQN — the substring before the last dot, or {@code ""} (default package). */
    private static String packageOf(String fqn) {
        int dot = fqn.lastIndexOf('.');
        return dot < 0 ? "" : fqn.substring(0, dot);
    }

    private static List<Class<?>> discoverBceClasses(ClassLoader cl) {
        var bceClasses = new ArrayList<Class<?>>();
        try {
            java.util.ServiceLoader.load(
                    jakarta.enterprise.inject.build.compatible.spi.BuildCompatibleExtension.class, cl)
                    .forEach(ext -> bceClasses.add(ext.getClass()));
        } catch (Exception ignored) {}
        return bceClasses;
    }

    private static List<Class<?>> loadArchiveClasses(
            io.vidocq.vauban.indexer.VaubanIndex index, ClassLoader cl) {
        var classes = new ArrayList<Class<?>>();
        for (var classInfo : index.getKnownClasses()) {
            try {
                classes.add(Class.forName(classInfo.name().value(), false, cl));
            } catch (ClassNotFoundException | NoClassDefFoundError _) {
                // NoClassDefFoundError: a transitive dependency referenced by this type
                // is absent from the classpath (e.g. jakarta.activation from microprofile-config-api).
                // We ignore it silently; the class will simply not be loaded for the
                // rest of the pipeline (BCE / proxy / interceptor). See VAU-MVN-001.
               // warnings.add("Failed to load class {} from classpath, ignoring: {}", classInfo.name().value());
            }
        }
        return classes;
    }
}
