/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.vauban.example.cdi1015.app;

import io.vidocq.vauban.example.cdi1015.lib.AuditLog;
import io.vidocq.vauban.example.cdi1015.lib.PaymentGateway;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;

/**
 * A bean that injects the two produced third-party types. Each injected reference is a normal-scoped
 * client proxy generated by Vauban at compile time — a {@code PaymentGateway} subclass and an
 * {@code AuditLog} implementation, both living in this module's package. No {@code opens}, no
 * runtime reflection.
 */
@ApplicationScoped
public class CheckoutService {

    // Package-private: the generated in-module provider field-injects it without any `opens`.
    @Inject
    PaymentGateway gateway;

    @Inject
    AuditLog audit;

    public String checkout(String account, String order, int cents) {
        audit.recordCheckout(order); // default method, through the interface proxy
        return gateway.charge(account, cents); // method, through the class proxy
    }
}
