package fr.vidocq.vauban.processor.codegen.factory;

import fr.vidocq.vauban.indexer.model.ClassInfo;
import fr.vidocq.vauban.indexer.scanner.ClassFileScanner;
import fr.vidocq.vauban.processor.codegen.GeneratedClass;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("BeanFactoryGenerator")
class BeanFactoryGeneratorTest {

    // Simple test class with no-arg constructor
    public static class SimpleBean {
        public String value = "hello";
    }

    static ClassInfo scanClass(Class<?> clazz) throws IOException {
        String resource = clazz.getName().replace('.', '/') + ".class";
        try (var is = clazz.getClassLoader().getResourceAsStream(resource)) {
            return ClassFileScanner.scan(is.readAllBytes());
        }
    }

    /**
     * Custom ClassLoader that loads from generated bytecode.
     */
    static class ByteArrayClassLoader extends ClassLoader {
        private final Map<String, byte[]> classes;

        ByteArrayClassLoader(ClassLoader parent, Map<String, byte[]> classes) {
            super(parent);
            this.classes = classes;
        }

        @Override
        protected Class<?> findClass(String name) throws ClassNotFoundException {
            var bytes = classes.get(name);
            if (bytes != null) return defineClass(name, bytes, 0, bytes.length);
            throw new ClassNotFoundException(name);
        }
    }

    @Nested
    @DisplayName("generation de factory pour bean no-arg")
    class NoArgBean {

        @Test
        @DisplayName("genere une classe factory valide")
        void shouldGenerateValidFactory() throws IOException {
            var classInfo = scanClass(SimpleBean.class);
            var generated = BeanFactoryGenerator.generate(classInfo);

            assertNotNull(generated);
            assertEquals(SimpleBean.class.getName() + "_Factory", generated.className());
            assertTrue(generated.bytecode().length > 0);
        }

        @Test
        @DisplayName("la factory generee peut etre chargee")
        void shouldLoadGeneratedFactory() throws Exception {
            var classInfo = scanClass(SimpleBean.class);
            var generated = BeanFactoryGenerator.generate(classInfo);

            var cl = new ByteArrayClassLoader(getClass().getClassLoader(),
                    Map.of(generated.className(), generated.bytecode()));
            var factoryClass = cl.loadClass(generated.className());
            assertNotNull(factoryClass);
        }

        @Test
        @DisplayName("la factory cree une instance du bean")
        void shouldCreateBeanInstance() throws Exception {
            var classInfo = scanClass(SimpleBean.class);
            var generated = BeanFactoryGenerator.generate(classInfo);

            var cl = new ByteArrayClassLoader(getClass().getClassLoader(),
                    Map.of(generated.className(), generated.bytecode()));
            var factoryClass = cl.loadClass(generated.className());
            var factory = factoryClass.getDeclaredConstructor().newInstance();

            // Call create() via the BeanFactory interface
            var createMethod = factoryClass.getMethod("create");
            var bean = createMethod.invoke(factory);

            assertNotNull(bean);
            assertInstanceOf(SimpleBean.class, bean);
            assertEquals("hello", ((SimpleBean) bean).value);
        }

        @Test
        @DisplayName("la factory implemente BeanFactory")
        void shouldImplementBeanFactory() throws Exception {
            var classInfo = scanClass(SimpleBean.class);
            var generated = BeanFactoryGenerator.generate(classInfo);

            var cl = new ByteArrayClassLoader(getClass().getClassLoader(),
                    Map.of(generated.className(), generated.bytecode()));
            var factoryClass = cl.loadClass(generated.className());

            assertTrue(fr.vidocq.vauban.core.BeanFactory.class.isAssignableFrom(factoryClass));

            @SuppressWarnings("unchecked")
            var factory = (fr.vidocq.vauban.core.BeanFactory<SimpleBean>)
                    factoryClass.getDeclaredConstructor().newInstance();
            var bean = factory.create();
            assertInstanceOf(SimpleBean.class, bean);
        }
    }
}
