/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.vauban.processor.codegen.factory;

import io.vidocq.vauban.indexer.model.ClassInfo;
import io.vidocq.vauban.indexer.scanner.ClassFileScanner;
import io.vidocq.vauban.processor.codegen.GeneratedClass;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("BeanFactoryGenerator")
class BeanFactoryGeneratorTest {

    // Simple test class with no-arg constructor
    public static class SimpleBean {
        public String value = "hello";
    }

    static ClassInfo scanClass(Class<?> clazz) throws IOException {
        String resource = clazz.getName().replace('.', '/') + ".class";
        try (var is = clazz.getClassLoader().getResourceAsStream(resource)) {
            return ClassFileScanner.scan(is.readAllBytes());
        }
    }

    /**
     * Custom ClassLoader that loads from generated bytecode.
     */
    static class ByteArrayClassLoader extends ClassLoader {
        private final Map<String, byte[]> classes;

        ByteArrayClassLoader(ClassLoader parent, Map<String, byte[]> classes) {
            super(parent);
            this.classes = classes;
        }

        @Override
        protected Class<?> findClass(String name) throws ClassNotFoundException {
            var bytes = classes.get(name);
            if (bytes != null) return defineClass(name, bytes, 0, bytes.length);
            throw new ClassNotFoundException(name);
        }
    }

    @Nested
    @DisplayName("factory generation for a no-arg bean")
    class NoArgBean {

        @Test
        @DisplayName("generates a valid factory class")
        void shouldGenerateValidFactory() throws IOException {
            var classInfo = scanClass(SimpleBean.class);
            var generated = BeanFactoryGenerator.generate(classInfo);

            assertNotNull(generated);
            assertEquals(SimpleBean.class.getName() + "_Factory", generated.className());
            assertTrue(generated.bytecode().length > 0);
        }

        @Test
        @DisplayName("the generated factory can be loaded")
        void shouldLoadGeneratedFactory() throws Exception {
            var classInfo = scanClass(SimpleBean.class);
            var generated = BeanFactoryGenerator.generate(classInfo);

            var cl = new ByteArrayClassLoader(getClass().getClassLoader(),
                    Map.of(generated.className(), generated.bytecode()));
            var factoryClass = cl.loadClass(generated.className());
            assertNotNull(factoryClass);
        }

        @Test
        @DisplayName("the factory creates a bean instance")
        void shouldCreateBeanInstance() throws Exception {
            var classInfo = scanClass(SimpleBean.class);
            var generated = BeanFactoryGenerator.generate(classInfo);

            var cl = new ByteArrayClassLoader(getClass().getClassLoader(),
                    Map.of(generated.className(), generated.bytecode()));
            var factoryClass = cl.loadClass(generated.className());
            var factory = factoryClass.getDeclaredConstructor().newInstance();

            // Call create() via the BeanFactory interface
            var createMethod = factoryClass.getMethod("create");
            var bean = createMethod.invoke(factory);

            assertNotNull(bean);
            assertInstanceOf(SimpleBean.class, bean);
            assertEquals("hello", ((SimpleBean) bean).value);
        }

        @Test
        @DisplayName("the factory implements BeanFactory")
        void shouldImplementBeanFactory() throws Exception {
            var classInfo = scanClass(SimpleBean.class);
            var generated = BeanFactoryGenerator.generate(classInfo);

            var cl = new ByteArrayClassLoader(getClass().getClassLoader(),
                    Map.of(generated.className(), generated.bytecode()));
            var factoryClass = cl.loadClass(generated.className());

            assertTrue(io.vidocq.vauban.core.BeanFactory.class.isAssignableFrom(factoryClass));

            @SuppressWarnings("unchecked")
            var factory = (io.vidocq.vauban.core.BeanFactory<SimpleBean>)
                    factoryClass.getDeclaredConstructor().newInstance();
            var bean = factory.create();
            assertInstanceOf(SimpleBean.class, bean);
        }
    }
}
